
; File generated by darts version O-2018.09#f5599cac26#190121, Tue May 28 10:43:39 2024
; Copyright 2014-2018 Synopsys, Inc. All rights reserved.
; darts -B -I../lib +p -d -h -I../lib/runtime/include -D__tct_patch__=300 +Ihex +u Release/sum_abs_diff tmicro

; Release: ipd O-2018.09-SP3

.text_segment PM      0	   
.entry_point
.label tmicro_init
	/*      0      0x241a */    	mvi sp,1 /* MW 2 */
	/*      1      0x0001 */    /* MW 1 */
.label _start_basic
	/*      2      0x2e98 */    	cl 18 /* MW 2 */
	/*      3      0x0012 */    /* MW 1 */
	/*      4      0x2e00 */    	nop 
	/*      5      0x2dff */    	jr -1
.label __sint_sum_abs_diff___P__sint___P__sint___sint
	/*      6      0x3000 */    	mvib r0,0
	/*      7      0x0e98 */    	le r3,r0
	/*      8      0x2f07 */    	jcr 7
	/*      9      0x2edb */    	do r3,16 /* MW 2 */
	/*     10      0x0010 */    /* MW 1 */
	/*     11      0x2e00 */    	nop 
	/*     12      0x4054 */    	ld r4,dm(r1++)
	/*     13      0x4095 */    	ld r5,dm(r2++)
	/*     14      0x0525 */    	sub r4,r4,r5
	/*     15      0xc120 */    	ext_abs r4,r4
	/*     16      0x0004 */    	add r0,r0,r4
	/*     17      0x2eb8 */    	rt 
.label _main
	/*     18      0x5050 */    	addb sp, 5
	/*     19      0x7fc1 */    	st r1,dm(sp-4)
	/*     20      0x7fdb */    	st lr,dm(sp-3)
	/*     21      0x7fb0 */    	st r0,dm(sp-5)
	/*     22      0x2412 */    	mvi r2,8202 /* MW 2 */
	/*     23      0x200a */    /* MW 1 */
	/*     24      0x30a3 */    	mvib r3,10
	/*     25      0x2411 */    	mvi r1,8192 /* MW 2 */
	/*     26      0x2000 */    /* MW 1 */
	/*     27      0x2e98 */    	cl 6 /* MW 2 */
	/*     28      0x0006 */    /* MW 1 */
	/*     29      0x6fb2 */    	ld r2,dm(sp-5)
	/*     30      0x0402 */    	sub r0,r0,r2
	/*     31      0x6fc2 */    	ld r2,dm(sp-4)
	/*     32      0x068a */    	subb r2,r1,r2
	/*     33      0x7ff2 */    	st r2,dm(sp-1)
	/*     34      0x7fe0 */    	st r0,dm(sp-2)
	/*     35      0x2411 */    	mvi r1,8212 /* MW 2 */
	/*     36      0x2014 */    /* MW 1 */
	/*     37      0x2e98 */    	cl 63 /* MW 2 */
	/*     38      0x003f */    /* MW 1 */
	/*     39      0x6fdb */    	ld lr,dm(sp-3)
	/*     40      0x2ec0 */    	rtd 
	/*     41      0x3000 */    	mvib r0,0
	/*     42      0x5fb0 */    	addb sp, -5
.label __stdio_void_clib_hosted_io___PHosted_clib_vars
	/*     43      0x2eb8 */    	rt 
.label vfprintf
	/*     44      0x5130 */    	addb sp, 19
	/*     45      0x250a */    	mv r0,sp
	/*     46      0x3ed4 */    	mvib r4,-19
	/*     47      0x4045 */    	ld r5,dm(r1)
	/*     48      0x0004 */    	add r0,r0,r4
	/*     49      0x3ff1 */    	mvib r1,-1
	/*     50      0x3024 */    	mvib r4,2
	/*     51      0x7ffb */    	st lr,dm(sp-1)
	/*     52      0x7ee5 */    	st r5,dm(sp-18)
	/*     53      0x7f22 */    	st r2,dm(sp-14)
	/*     54      0x7fe3 */    	st r3,dm(sp-2)
	/*     55      0x7ef1 */    	st r1,dm(sp-17)
	/*     56      0x4204 */    	st r4,dm(r0)
	/*     57      0x2e98 */    	cl 43 /* MW 2 */
	/*     58      0x002b */    /* MW 1 */
	/*     59      0x6ffb */    	ld lr,dm(sp-1)
	/*     60      0x2ec0 */    	rtd 
	/*     61      0x6ef0 */    	ld r0,dm(sp-17)
	/*     62      0x5ed0 */    	addb sp, -19
.label printf
	/*     63      0x2410 */    	mvi r0,8270 /* MW 2 */
	/*     64      0x204e */    /* MW 1 */
	/*     65      0x253a */    	mv r3,sp
	/*     66      0x3004 */    	mvib r4,0
	/*     67      0x2521 */    	mv r2,r1
	/*     68      0x4001 */    	ld r1,dm(r0)
	/*     69      0x00dc */    	add r3,r3,r4
	/*     70      0x2e80 */    	j 44 /* MW 2 */
	/*     71      0x002c */    /* MW 1 */

.data_segment DM   8192	   
.label arrayA
	0xfff1
	0xffec
	0x1e
	0x28
	0x3c
	0xfed4
	0x23
	0x2d
	0x11d
	0x50
.label arrayB
	0xfff2
	0xffeb
	0x1f
	0x27
	0x3b
	0xfed5
	0x24
	0x2e
	0x11e
	0x51

.rodata_segment DM   8212	   
.label __sum_abs_diff___str0390394d
	0x45
	0x78
	0x65
	0x63
	0x75
	0x74
	0x69
	0x6f
	0x6e
	0x20
	0x74
	0x69
	0x6d
	0x65
	0x20
	0x66
	0x6f
	0x72
	0x20
	0x73
	0x75
	0x6d
	0x5f
	0x61
	0x62
	0x73
	0x5f
	0x64
	0x69
	0x66
	0x66
	0x20
	0x66
	0x75
	0x6e
	0x63
	0x74
	0x69
	0x6f
	0x6e
	0x20
	0x69
	0x73
	0x20
	0x25
	0x6c
	0x64
	0x20
	0x63
	0x79
	0x63
	0x6c
	0x65
	0x73
	0xa
	0x0

.data_segment DM   8268	   
.label __stdio__stdout
	0x1
	0x1
.label stdout
	0x204c

.bss_segment DM   8271	    256

.stack DM 1 8192
