
// File generated by noodle version O-2018.09#f5599cac26#190121, Tue May 28 10:41:29 2024
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// noodle -Pc -B -Iisg +wisg -Iruntime/include -D__tct_patch__=300 -D__chess__ -D__programmers_view__ tmicro

#ifdef __chess__
#error "generated native file not intended for compilation by chess"
#endif

// Native equivalent of Chess promoted operations

#include "tmicro_iss_types.h"
#include "tmicro_chess_types.h"
#include "tmicro_inline_primitives.h"
#include "tmicro_chess_opns.h"

#ifndef CHESS_NATIVE_LINKAGE
#define CHESS_NATIVE_LINKAGE
#endif

#ifdef CHESS_NATIVE_NAMESPACE
namespace CHESS_NATIVE_NAMESPACE {
#endif

namespace tmicro_primitive{
    CHESS_NATIVE_LINKAGE word mul(word a, word b)
    {
     word x; word y;
     mulss(a,b,x,y);
     return x;
    }
} //namespace tmicro_primitive

CHESS_NATIVE_LINKAGE void divstep(unsigned a0, unsigned a1, unsigned a2, unsigned & a3, unsigned & a4)
{
    tmicro_primitive::word p0 = a0;
    tmicro_primitive::word p1 = a1;
    tmicro_primitive::word p2 = a2;
    tmicro_primitive::word p3; //output
    tmicro_primitive::word p4; //output
    tmicro_primitive::divstep(p0, p1, p2, p3, p4);
    a3 = toVBit(p3).value();
    a4 = toVBit(p4).value();
}

namespace tmicro_primitive{
CHESS_NATIVE_LINKAGE int extend_sign(int a0)
{
    word p0 = a0;
    word t = extend_sign(p0);
    int r; r = toVBit(t).value();
    return r;
}
} //namespace tmicro_primitive

#if 0//!
namespace tmicro_primitive{
    CHESS_NATIVE_LINKAGE dint to_dint_se(int i)
    {
     return dint(i,extend_sign(i));
    }
} //namespace tmicro_primitive
#endif//!

#if 0//!
namespace tmicro_primitive{
    CHESS_NATIVE_LINKAGE dint to_dint_ze(int i)
    {
     return dint(i,0);
    }
} //namespace tmicro_primitive
#endif//!

#if 0//!
namespace tmicro_primitive{
    CHESS_NATIVE_LINKAGE int to_int(dint w)
    {
     return w.lo;
    }
} //namespace tmicro_primitive
#endif//!

namespace tmicro_primitive{
CHESS_NATIVE_LINKAGE unsigned add(unsigned a0, unsigned a1, uint1 & a2)
{
    word p0 = a0;
    word p1 = a1;
    uint1 p2; //output
    word t = add(p0, p1, p2);
    a2 = p2;
    unsigned r; r = toVBit(t).value();
    return r;
}
} //namespace tmicro_primitive

namespace tmicro_primitive{
CHESS_NATIVE_LINKAGE unsigned addc(unsigned a0, unsigned a1, uint1 a2, uint1 & a3)
{
    word p0 = a0;
    word p1 = a1;
    uint1 p2 = a2;
    uint1 p3; //output
    word t = addc(p0, p1, p2, p3);
    a3 = p3;
    unsigned r; r = toVBit(t).value();
    return r;
}
} //namespace tmicro_primitive

namespace tmicro_primitive{
CHESS_NATIVE_LINKAGE unsigned sub(unsigned a0, unsigned a1, uint1 & a2)
{
    word p0 = a0;
    word p1 = a1;
    uint1 p2; //output
    word t = sub(p0, p1, p2);
    a2 = p2;
    unsigned r; r = toVBit(t).value();
    return r;
}
} //namespace tmicro_primitive

namespace tmicro_primitive{
CHESS_NATIVE_LINKAGE unsigned subb(unsigned a0, unsigned a1, uint1 a2, uint1 & a3)
{
    word p0 = a0;
    word p1 = a1;
    uint1 p2 = a2;
    uint1 p3; //output
    word t = subb(p0, p1, p2, p3);
    a3 = p3;
    unsigned r; r = toVBit(t).value();
    return r;
}
} //namespace tmicro_primitive

#if 0//!
namespace tmicro_primitive{
    CHESS_NATIVE_LINKAGE dint l_add(dint a, dint b)
    {
     dint r;
     uint1 carry; uint1 carry2;
     r.lo = add(a.lo,b.lo,carry);
     r.hi = addc(a.hi,b.hi,carry,carry2);
     return r;
    }
} //namespace tmicro_primitive
#endif//!

#if 0//!
namespace tmicro_primitive{
    CHESS_NATIVE_LINKAGE dint l_sub(dint a, dint b)
    {
     dint r;
     uint1 borrow; uint1 borrow2;
     r.lo = sub(a.lo,b.lo,borrow);
     r.hi = subb(a.hi,b.hi,borrow,borrow2);
     return r;
    }
} //namespace tmicro_primitive
#endif//!

#if 0//!
namespace tmicro_primitive{
    CHESS_NATIVE_LINKAGE dint l_and(dint a, dint b)
    {
     return dint(a.lo & b.lo,a.hi & b.hi);
    }
} //namespace tmicro_primitive
#endif//!

#if 0//!
namespace tmicro_primitive{
    CHESS_NATIVE_LINKAGE dint l_or(dint a, dint b)
    {
     return dint(a.lo | b.lo,a.hi | b.hi);
    }
} //namespace tmicro_primitive
#endif//!

#if 0//!
namespace tmicro_primitive{
    CHESS_NATIVE_LINKAGE dint l_xor(dint a, dint b)
    {
     return dint(a.lo ^ b.lo,a.hi ^ b.hi);
    }
} //namespace tmicro_primitive
#endif//!

#if 0//!
namespace tmicro_primitive{
    CHESS_NATIVE_LINKAGE dint l_complement(dint a)
    {
     return dint(~a.lo,~a.hi);
    }
} //namespace tmicro_primitive
#endif//!

namespace tmicro_primitive{
CHESS_NATIVE_LINKAGE void mulss(int a0, int a1, int & a2, int & a3)
{
    word p0 = a0;
    word p1 = a1;
    word p2; //output
    word p3; //output
    mulss(p0, p1, p2, p3);
    a2 = toVBit(p2).value();
    a3 = toVBit(p3).value();
}
} //namespace tmicro_primitive

namespace tmicro_primitive{
CHESS_NATIVE_LINKAGE void muluu(int a0, int a1, int & a2, int & a3)
{
    word p0 = a0;
    word p1 = a1;
    word p2; //output
    word p3; //output
    muluu(p0, p1, p2, p3);
    a2 = toVBit(p2).value();
    a3 = toVBit(p3).value();
}
} //namespace tmicro_primitive

#if 0//!
namespace tmicro_primitive{
    CHESS_NATIVE_LINKAGE dint l_mul(dint a, dint b)
    {
     int x = 0; int y = 0;
     if (!chess_manifest(a.lo == 0) && !chess_manifest(b.lo == 0))
      muluu(a.lo,b.lo,x,y);
     else
      ;
     y += a.hi * b.lo;
     y += b.hi * a.lo;
     return dint(x,y);
    }
} //namespace tmicro_primitive
#endif//!

#if 0//!
namespace tmicro_primitive{
    CHESS_NATIVE_LINKAGE dint di_mul(int a, int b)
    {
     int x; int y;
     mulss(a,b,x,y);
     return dint(x,y);
    }
} //namespace tmicro_primitive
#endif//!

#if 0//!
CHESS_NATIVE_LINKAGE long lmul(int a0, int a1)
{
    int p0 = a0;
    int p1 = a1;
    tmicro_primitive::dint t = tmicro_primitive::di_mul(p0, p1);
    long r; r = toVBit(t).value();
    return r;
}
#endif//!

#if 0//!
namespace tmicro_primitive{
    CHESS_NATIVE_LINKAGE bool lts(dint a, dint b)
    {
     if ((int)a.hi < (int)b.hi)
      return true;
     else
      if (a.hi == b.hi)
       return a.lo < b.lo;
      else
       return false;
    }
} //namespace tmicro_primitive
#endif//!

#if 0//!
namespace tmicro_primitive{
    CHESS_NATIVE_LINKAGE bool les(dint a, dint b)
    {
     if ((int)a.hi < (int)b.hi)
      return true;
     else
      if (a.hi == b.hi)
       return a.lo <= b.lo;
      else
       return false;
    }
} //namespace tmicro_primitive
#endif//!

#if 0//!
namespace tmicro_primitive{
    CHESS_NATIVE_LINKAGE bool ltu(dint a, dint b)
    {
     if ((unsigned)a.hi < (unsigned)b.hi)
      return true;
     else
      if (a.hi == b.hi)
       return a.lo < b.lo;
      else
       return false;
    }
} //namespace tmicro_primitive
#endif//!

#if 0//!
namespace tmicro_primitive{
    CHESS_NATIVE_LINKAGE bool leu(dint a, dint b)
    {
     if ((unsigned)a.hi < (unsigned)b.hi)
      return true;
     else
      if (a.hi == b.hi)
       return a.lo <= b.lo;
      else
       return false;
    }
} //namespace tmicro_primitive
#endif//!

#if 0//!
namespace tmicro_primitive{
    CHESS_NATIVE_LINKAGE bool eq(dint a, dint b)
    {
     return a.hi == b.hi && a.lo == b.lo;
    }
} //namespace tmicro_primitive
#endif//!

#if 0//!
namespace tmicro_primitive{
    CHESS_NATIVE_LINKAGE bool ne(dint a, dint b)
    {
     return a.hi != b.hi || a.lo != b.lo;
    }
} //namespace tmicro_primitive
#endif//!

#if 0//!
namespace tmicro_primitive{
    CHESS_NATIVE_LINKAGE dint l_lsl(dint a, int f)
    {
     unsigned carries;
     dint r;
     if (chess_manifest(f == 1))
      {
       return l_add(a,a);
      }
     else
      ;
     if (f == 0)
      return a;
     else
      ;
     if (f < 16)
      {
       carries = a.lo >> 16 - f;
       r.lo = chess_dont_warn_range(a.lo << f);
       r.hi = chess_dont_warn_range(a.hi << f) | carries;
      }
     else
      {
       carries = a.lo << f - 16;
       r.lo = 0;
       r.hi = carries;
      }
     return r;
    }
} //namespace tmicro_primitive
#endif//!

#if 0//!
namespace tmicro_primitive{
    CHESS_NATIVE_LINKAGE dint l_asr(dint a, int f)
    {
     unsigned carries;
     dint r;
     if (f == 0)
      return a;
     else
      ;
     if (f < 16)
      {
       carries = a.hi << 16 - f;
       r.lo = chess_dont_warn_range(a.lo >> f) | carries;
       r.hi = chess_dont_warn_range((int)a.hi >> f);
      }
     else
      {
       carries = (int)a.hi >> f - 16;
       r.lo = carries;
       r.hi = extend_sign(r.lo);
      }
     return r;
    }
} //namespace tmicro_primitive
#endif//!

#if 0//!
namespace tmicro_primitive{
    CHESS_NATIVE_LINKAGE dint l_lsr(dint a, int f)
    {
     unsigned carries;
     dint r;
     if (f == 0)
      return a;
     else
      ;
     if (f < 16)
      {
       carries = a.hi << 16 - f;
       r.lo = chess_dont_warn_range(a.lo >> f) | carries;
       r.hi = chess_dont_warn_range(a.hi >> f);
      }
     else
      {
       carries = a.hi >> f - 16;
       r.lo = carries;
       r.hi = 0;
      }
     return r;
    }
} //namespace tmicro_primitive
#endif//!

#if 0//!
namespace tmicro_primitive{
    CHESS_NATIVE_LINKAGE long div_remainder(long a, long b, long &r)
    {
     return div_called(a,b,r);
    }
} //namespace tmicro_primitive
#endif//!

#if 0//!
namespace tmicro_primitive{
    CHESS_NATIVE_LINKAGE unsigned long div_remainder(unsigned long a, unsigned long b, unsigned long &r)
    {
     return div_called(a,b,r);
    }
} //namespace tmicro_primitive
#endif//!

CHESS_NATIVE_LINKAGE int min_(int a0, int a1)
{
    tmicro_primitive::word p0 = a0;
    tmicro_primitive::word p1 = a1;
    tmicro_primitive::word t = tmicro_primitive::minw(p0, p1);
    int r; r = toVBit(t).value();
    return r;
}

CHESS_NATIVE_LINKAGE int max_(int a0, int a1)
{
    tmicro_primitive::word p0 = a0;
    tmicro_primitive::word p1 = a1;
    tmicro_primitive::word t = tmicro_primitive::maxw(p0, p1);
    int r; r = toVBit(t).value();
    return r;
}

CHESS_NATIVE_LINKAGE int select(bool a0, int a1, int a2)
{
    bool p0 = a0;
    tmicro_primitive::word p1 = a1;
    tmicro_primitive::word p2 = a2;
    tmicro_primitive::word t = tmicro_primitive::select(p0, p1, p2);
    int r; r = toVBit(t).value();
    return r;
}

CHESS_NATIVE_LINKAGE unsigned select(bool a0, unsigned a1, unsigned a2)
{
    bool p0 = a0;
    tmicro_primitive::word p1 = a1;
    tmicro_primitive::word p2 = a2;
    tmicro_primitive::word t = tmicro_primitive::select(p0, p1, p2);
    unsigned r; r = toVBit(t).value();
    return r;
}

CHESS_NATIVE_LINKAGE int ext_abs_(int a0)
{
    tmicro_primitive::word p0 = a0;
    tmicro_primitive::word t = tmicro_primitive::ext_abs(p0);
    int r; r = toVBit(t).value();
    return r;
}


#ifdef CHESS_NATIVE_NAMESPACE
} //namespace CHESS_NATIVE_NAMESPACE
#endif
