
// File generated by Go version O-2018.09#f5599cac26#190121, Tue May 28 10:45:21 2024
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// go -B -I../lib -F -D__tct_patch__=300 -Verilog -otmicro_vlog -cgo_options.cfg -Itmicro_vlog/tmp_pdg -updg -updg_controller tmicro



`timescale 1ns/1ps

// module ag1 : ag1
module ag1
  ( input                    ohe_selector_ID,
    input      signed [15:0] ag1m_in, // word
    input      signed [15:0] ag1p_in, // word
    output reg signed [15:0] ag1q_out // word
  );


`include "primitives.v"

  always @ (*)

  begin : p_ag1


    reg    signed [15:0] ag1m; // word
    reg    signed [15:0] ag1p; // word

    ag1q_out = 0;

    // operand isolation
    if (ohe_selector_ID == 0)
    begin
      ag1m = 0;
      ag1p = 0;
    end
    else
    begin
      ag1m = ag1m_in;
      ag1p = ag1p_in;
    end


    if (ohe_selector_ID) // (ag1q_add_ag1p_ag1m_ag1_ID)
    begin
      // [load_store.n:46][load_store.n:76][load_store.n:77][load_store.n:138][load_store.n:145]
      word_add_word_word(ag1q_out, ag1p, ag1m);
    end

  end

endmodule
