
// File generated by Go version O-2018.09#f5599cac26#190121, Tue May 28 10:45:21 2024
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// go -B -I../lib -F -D__tct_patch__=300 -Verilog -otmicro_vlog -cgo_options.cfg -Itmicro_vlog/tmp_pdg -updg -updg_controller tmicro



`timescale 1ns/1ps

// module dlflg : dlflg
module dlflg
  ( input      [1:0] bin_selector_E1,
    input      [1:0] lfr_in, // uint2
    output reg [1:0] lfw_out // uint2
  );


  parameter sel_decr_uint2 = 2'b01;
  parameter sel_incr_uint2 = 2'b10;

`include "primitives.v"

  always @ (*)

  begin : p_dlflg


    reg    [1:0] lfr; // uint2

    lfw_out = 0;

    // operand isolation
    if (bin_selector_E1 == 0)
    begin
      lfr = 0;
    end
    else
    begin
      lfr = lfr_in;
    end


    case (bin_selector_E1)
      sel_decr_uint2 : // (lfw_decr_lfr_dlflg_E1)
      begin
        // [control.n:211]
        uint2_decr_uint2(lfw_out, lfr);
      end
      sel_incr_uint2 : // (lfw_incr_lfr_dlflg_E1)
      begin
        // [control.n:177]
        uint2_incr_uint2(lfw_out, lfr);
      end
      default :
        ; // null
    endcase

  end

endmodule
