
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2024 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xfilt_bp_hw.h"

/*
* The configuration table for devices
*/

XFilt_bp_hw_Config XFilt_bp_hw_ConfigTable[XPAR_XFILT_BP_HW_NUM_INSTANCES] =
{
	{
		XPAR_FILT_BP_HW_1_DEVICE_ID,
		XPAR_FILT_BP_HW_1_S_AXI_CONTROL_BASEADDR
	}
};


