
// File generated by noodle version O-2018.09#f5599cac26#190121, Tue May 28 10:41:29 2024
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// noodle -Pc -B -Iisg +wisg -Iruntime/include -D__tct_patch__=300 -D__chess__ -D__programmers_view__ tmicro

// File: builtin_operators.c
// Test C built-in operators  (except any left undefined)
// (Reference in-out argument avoids additional moves i.c.o. read-modify-write)

#ifndef N // arbitrary value, adapt at will
#define N 13
#endif

extern "C" {

//-- int

void biopr___sint__pl(int& a, int b) { a += b; }
void biopr___sint__mi(int& a, int b) { a -= b; }
void biopr___sint__ml(int& a, int b) { a *= b; }
void biopr___sint__dv(int& a, int b) { a /= b; }
void biopr___sint__md(int& a, int b) { a %= b; }
void biopr___sint__ad(int& a, int b) { a &= b; }
void biopr___sint__or(int& a, int b) { a |= b; }
void biopr___sint__er(int& a, int b) { a ^= b; }
void biopr___sint__ls(int& a, int b) { a <<= b; }
void biopr___sint__rs(int& a, int b) { a >>= b; }
void biopr___sint__co(int& a) { a = ~a; }

void biopr___sint__plN(int& a) { a += N; }
void biopr___sint__miN(int& a) { a -= N; }
void biopr___sint__mlN(int& a) { a *= N; }
void biopr___sint__dvN(int& a) { a /= N; }
void biopr___sint__mdN(int& a) { a %= N; }
void biopr___sint__adN(int& a) { a &= N; }
void biopr___sint__orN(int& a) { a |= N; }
void biopr___sint__erN(int& a) { a ^= N; }
void biopr___sint__lsN(int& a) { a <<= N; }
void biopr___sint__rsN(int& a) { a >>= N; }

void biopr___sint__miR(int& a) { a = N - a; }
void biopr___sint__lsR(int& a) { a = N << a; }
void biopr___sint__rsR(int& a) { a = N >> a; }

int  biopr___sint__lt(int a, int b) { return a < b; }
int  biopr___sint__gt(int a, int b) { return a > b; }
int  biopr___sint__le(int a, int b) { return a <= b; }
int  biopr___sint__ge(int a, int b) { return a >= b; }
int  biopr___sint__eq(int a, int b) { return a == b; }
int  biopr___sint__ne(int a, int b) { return a != b; }

int  biopr___sint__ltN(int a) { return a < N; }
int  biopr___sint__gtN(int a) { return a > N; }
int  biopr___sint__leN(int a) { return a <= N; }
int  biopr___sint__geN(int a) { return a >= N; }
int  biopr___sint__eqN(int a) { return a == N; }
int  biopr___sint__neN(int a) { return a != N; }

//-- unsigned

void biopr___uint__pl(unsigned& a, unsigned b) { a += b; }
void biopr___uint__mi(unsigned& a, unsigned b) { a -= b; }
void biopr___uint__ml(unsigned& a, unsigned b) { a *= b; }
void biopr___uint__dv(unsigned& a, unsigned b) { a /= b; }
void biopr___uint__md(unsigned& a, unsigned b) { a %= b; }
void biopr___uint__ad(unsigned& a, unsigned b) { a &= b; }
void biopr___uint__or(unsigned& a, unsigned b) { a |= b; }
void biopr___uint__er(unsigned& a, unsigned b) { a ^= b; }
void biopr___uint__ls(unsigned& a, int b) { a <<= b; }
void biopr___uint__rs(unsigned& a, int b) { a >>= b; }
void biopr___uint__co(unsigned& a) { a = ~a; }

void biopr___uint__plN(unsigned& a) { a += N; }
void biopr___uint__miN(unsigned& a) { a -= N; }
void biopr___uint__mlN(unsigned& a) { a *= N; }
void biopr___uint__dvN(unsigned& a) { a /= N; }
void biopr___uint__mdN(unsigned& a) { a %= N; }
void biopr___uint__adN(unsigned& a) { a &= N; }
void biopr___uint__orN(unsigned& a) { a |= N; }
void biopr___uint__erN(unsigned& a) { a ^= N; }
void biopr___uint__lsN(unsigned& a) { a <<= N; }
void biopr___uint__rsN(unsigned& a) { a >>= N; }

void biopr___uint__miR(unsigned& a) { a = N - a; }
void biopr___uint__lsR(unsigned& a) { a = N << a; }
void biopr___uint__rsR(unsigned& a) { a = N >> a; }

int  biopr___uint__lt(unsigned a, unsigned b) { return a < b; }
int  biopr___uint__gt(unsigned a, unsigned b) { return a > b; }
int  biopr___uint__le(unsigned a, unsigned b) { return a <= b; }
int  biopr___uint__ge(unsigned a, unsigned b) { return a >= b; }
int  biopr___uint__eq(unsigned a, unsigned b) { return a == b; }
int  biopr___uint__ne(unsigned a, unsigned b) { return a != b; }

int  biopr___uint__ltN(unsigned a) { return a < N; }
int  biopr___uint__gtN(unsigned a) { return a > N; }
int  biopr___uint__leN(unsigned a) { return a <= N; }
int  biopr___uint__geN(unsigned a) { return a >= N; }
int  biopr___uint__eqN(unsigned a) { return a == N; }
int  biopr___uint__neN(unsigned a) { return a != N; }

//-- long

void biopr___slong__pl(long& a, long b) { a += b; }
void biopr___slong__mi(long& a, long b) { a -= b; }
void biopr___slong__ml(long& a, long b) { a *= b; }
void biopr___slong__dv(long& a, long b) { a /= b; }
void biopr___slong__md(long& a, long b) { a %= b; }
void biopr___slong__ad(long& a, long b) { a &= b; }
void biopr___slong__or(long& a, long b) { a |= b; }
void biopr___slong__er(long& a, long b) { a ^= b; }
void biopr___slong__ls(long& a, int b) { a <<= b; }
void biopr___slong__rs(long& a, int b) { a >>= b; }
void biopr___slong__co(long& a) { a = ~a; }

void biopr___slong__plN(long& a) { a += N; }
void biopr___slong__miN(long& a) { a -= N; }
void biopr___slong__mlN(long& a) { a *= N; }
void biopr___slong__dvN(long& a) { a /= N; }
void biopr___slong__mdN(long& a) { a %= N; }
void biopr___slong__adN(long& a) { a &= N; }
void biopr___slong__orN(long& a) { a |= N; }
void biopr___slong__erN(long& a) { a ^= N; }
void biopr___slong__lsN(long& a) { a <<= N; }
void biopr___slong__rsN(long& a) { a >>= N; }

void biopr___slong__miR(long& a) { a = N - a; }
void biopr___slong__lsR(long& a) { a = N << a; }
void biopr___slong__rsR(long& a) { a = N >> a; }

int  biopr___slong__lt(long a, long b) { return a < b; }
int  biopr___slong__gt(long a, long b) { return a > b; }
int  biopr___slong__le(long a, long b) { return a <= b; }
int  biopr___slong__ge(long a, long b) { return a >= b; }
int  biopr___slong__eq(long a, long b) { return a == b; }
int  biopr___slong__ne(long a, long b) { return a != b; }

int  biopr___slong__ltN(long a) { return a < N; }
int  biopr___slong__gtN(long a) { return a > N; }
int  biopr___slong__leN(long a) { return a <= N; }
int  biopr___slong__geN(long a) { return a >= N; }
int  biopr___slong__eqN(long a) { return a == N; }
int  biopr___slong__neN(long a) { return a != N; }

//-- unsigned long

void biopr___ulong__pl(unsigned long& a, unsigned long b) { a += b; }
void biopr___ulong__mi(unsigned long& a, unsigned long b) { a -= b; }
void biopr___ulong__ml(unsigned long& a, unsigned long b) { a *= b; }
void biopr___ulong__dv(unsigned long& a, unsigned long b) { a /= b; }
void biopr___ulong__md(unsigned long& a, unsigned long b) { a %= b; }
void biopr___ulong__ad(unsigned long& a, unsigned long b) { a &= b; }
void biopr___ulong__or(unsigned long& a, unsigned long b) { a |= b; }
void biopr___ulong__er(unsigned long& a, unsigned long b) { a ^= b; }
void biopr___ulong__ls(unsigned long& a, int b) { a <<= b; }
void biopr___ulong__rs(unsigned long& a, int b) { a >>= b; }
void biopr___ulong__co(unsigned long& a) { a = ~a; }

void biopr___ulong__plN(unsigned long& a) { a += N; }
void biopr___ulong__miN(unsigned long& a) { a -= N; }
void biopr___ulong__mlN(unsigned long& a) { a *= N; }
void biopr___ulong__dvN(unsigned long& a) { a /= N; }
void biopr___ulong__mdN(unsigned long& a) { a %= N; }
void biopr___ulong__adN(unsigned long& a) { a &= N; }
void biopr___ulong__orN(unsigned long& a) { a |= N; }
void biopr___ulong__erN(unsigned long& a) { a ^= N; }
void biopr___ulong__lsN(unsigned long& a) { a <<= N; }
void biopr___ulong__rsN(unsigned long& a) { a >>= N; }

void biopr___ulong__miR(unsigned long& a) { a = N - a; }
void biopr___ulong__lsR(unsigned long& a) { a = N << a; }
void biopr___ulong__rsR(unsigned long& a) { a = N >> a; }

int  biopr___ulong__lt(unsigned long a, unsigned long b) { return a < b; }
int  biopr___ulong__gt(unsigned long a, unsigned long b) { return a > b; }
int  biopr___ulong__le(unsigned long a, unsigned long b) { return a <= b; }
int  biopr___ulong__ge(unsigned long a, unsigned long b) { return a >= b; }
int  biopr___ulong__eq(unsigned long a, unsigned long b) { return a == b; }
int  biopr___ulong__ne(unsigned long a, unsigned long b) { return a != b; }

int  biopr___ulong__ltN(unsigned long a) { return a < N; }
int  biopr___ulong__gtN(unsigned long a) { return a > N; }
int  biopr___ulong__leN(unsigned long a) { return a <= N; }
int  biopr___ulong__geN(unsigned long a) { return a >= N; }
int  biopr___ulong__eqN(unsigned long a) { return a == N; }
int  biopr___ulong__neN(unsigned long a) { return a != N; }

//-- long long

//!! biopr___slonglong__pl(long long& a, long long b) { a += b; }
//!! biopr___slonglong__mi(long long& a, long long b) { a -= b; }
//!! biopr___slonglong__ml(long long& a, long long b) { a *= b; }
//!! biopr___slonglong__dv(long long& a, long long b) { a /= b; }
//!! biopr___slonglong__md(long long& a, long long b) { a %= b; }
//!! biopr___slonglong__ad(long long& a, long long b) { a &= b; }
//!! biopr___slonglong__or(long long& a, long long b) { a |= b; }
//!! biopr___slonglong__er(long long& a, long long b) { a ^= b; }
//!! biopr___slonglong__ls(long long& a, int b) { a <<= b; }
//!! biopr___slonglong__rs(long long& a, int b) { a >>= b; }
//!! biopr___slonglong__co(long long& a) { a = ~a; }

//!! biopr___slonglong__plN(long long& a) { a += N; }
//!! biopr___slonglong__miN(long long& a) { a -= N; }
//!! biopr___slonglong__mlN(long long& a) { a *= N; }
//!! biopr___slonglong__dvN(long long& a) { a /= N; }
//!! biopr___slonglong__mdN(long long& a) { a %= N; }
//!! biopr___slonglong__adN(long long& a) { a &= N; }
//!! biopr___slonglong__orN(long long& a) { a |= N; }
//!! biopr___slonglong__erN(long long& a) { a ^= N; }
//!! biopr___slonglong__lsN(long long& a) { a <<= N; }
//!! biopr___slonglong__rsN(long long& a) { a >>= N; }

//!! biopr___slonglong__miR(long long& a) { a = N - a; }
//!! biopr___slonglong__lsR(long long& a) { a = N << a; }
//!! biopr___slonglong__rsR(long long& a) { a = N >> a; }

//!! biopr___slonglong__lt(long long a, long long b) { return a < b; }
//!! biopr___slonglong__gt(long long a, long long b) { return a > b; }
//!! biopr___slonglong__le(long long a, long long b) { return a <= b; }
//!! biopr___slonglong__ge(long long a, long long b) { return a >= b; }
//!! biopr___slonglong__eq(long long a, long long b) { return a == b; }
//!! biopr___slonglong__ne(long long a, long long b) { return a != b; }

//!! biopr___slonglong__ltN(long long a) { return a < N; }
//!! biopr___slonglong__gtN(long long a) { return a > N; }
//!! biopr___slonglong__leN(long long a) { return a <= N; }
//!! biopr___slonglong__geN(long long a) { return a >= N; }
//!! biopr___slonglong__eqN(long long a) { return a == N; }
//!! biopr___slonglong__neN(long long a) { return a != N; }

//-- unsigned long long

//!! biopr___ulonglong__pl(unsigned long long& a, unsigned long long b) { a += b; }
//!! biopr___ulonglong__mi(unsigned long long& a, unsigned long long b) { a -= b; }
//!! biopr___ulonglong__ml(unsigned long long& a, unsigned long long b) { a *= b; }
//!! biopr___ulonglong__dv(unsigned long long& a, unsigned long long b) { a /= b; }
//!! biopr___ulonglong__md(unsigned long long& a, unsigned long long b) { a %= b; }
//!! biopr___ulonglong__ad(unsigned long long& a, unsigned long long b) { a &= b; }
//!! biopr___ulonglong__or(unsigned long long& a, unsigned long long b) { a |= b; }
//!! biopr___ulonglong__er(unsigned long long& a, unsigned long long b) { a ^= b; }
//!! biopr___ulonglong__ls(unsigned long long& a, int b) { a <<= b; }
//!! biopr___ulonglong__rs(unsigned long long& a, int b) { a >>= b; }
//!! biopr___ulonglong__co(unsigned long long& a) { a = ~a; }

//!! biopr___ulonglong__plN(unsigned long long& a) { a += N; }
//!! biopr___ulonglong__miN(unsigned long long& a) { a -= N; }
//!! biopr___ulonglong__mlN(unsigned long long& a) { a *= N; }
//!! biopr___ulonglong__dvN(unsigned long long& a) { a /= N; }
//!! biopr___ulonglong__mdN(unsigned long long& a) { a %= N; }
//!! biopr___ulonglong__adN(unsigned long long& a) { a &= N; }
//!! biopr___ulonglong__orN(unsigned long long& a) { a |= N; }
//!! biopr___ulonglong__erN(unsigned long long& a) { a ^= N; }
//!! biopr___ulonglong__lsN(unsigned long long& a) { a <<= N; }
//!! biopr___ulonglong__rsN(unsigned long long& a) { a >>= N; }

//!! biopr___ulonglong__miR(unsigned long long& a) { a = N - a; }
//!! biopr___ulonglong__lsR(unsigned long long& a) { a = N << a; }
//!! biopr___ulonglong__rsR(unsigned long long& a) { a = N >> a; }

//!! biopr___ulonglong__lt(unsigned long long a, unsigned long long b) { return a < b; }
//!! biopr___ulonglong__gt(unsigned long long a, unsigned long long b) { return a > b; }
//!! biopr___ulonglong__le(unsigned long long a, unsigned long long b) { return a <= b; }
//!! biopr___ulonglong__ge(unsigned long long a, unsigned long long b) { return a >= b; }
//!! biopr___ulonglong__eq(unsigned long long a, unsigned long long b) { return a == b; }
//!! biopr___ulonglong__ne(unsigned long long a, unsigned long long b) { return a != b; }

//!! biopr___ulonglong__ltN(unsigned long long a) { return a < N; }
//!! biopr___ulonglong__gtN(unsigned long long a) { return a > N; }
//!! biopr___ulonglong__leN(unsigned long long a) { return a <= N; }
//!! biopr___ulonglong__geN(unsigned long long a) { return a >= N; }
//!! biopr___ulonglong__eqN(unsigned long long a) { return a == N; }
//!! biopr___ulonglong__neN(unsigned long long a) { return a != N; }


} //extern "C"  (216 functions of which 72 skipped)
