
// File generated by noodle version O-2018.09#f5599cac26#190121, Tue May 28 10:41:29 2024
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// noodle -Pc -B -Iisg +wisg -Iruntime/include -D__tct_patch__=300 -D__chess__ -D__programmers_view__ tmicro

// File: builtin_conversions.c
// Test C built-in conversions  (except any left undefined)

extern "C" {


//-- int

int                 bicnv___sint___uint           (unsigned            a) { return a; }
int                 bicnv___sint___slong          (long                a) { return a; }
int                 bicnv___sint___ulong          (unsigned long       a) { return a; }
//!int                 bicnv___sint___slonglong      (long long           a) { return a; }
//!int                 bicnv___sint___ulonglong      (unsigned long long  a) { return a; }

//-- unsigned

unsigned            bicnv___uint___sint           (int                 a) { return a; }
unsigned            bicnv___uint___slong          (long                a) { return a; }
unsigned            bicnv___uint___ulong          (unsigned long       a) { return a; }
//!unsigned            bicnv___uint___slonglong      (long long           a) { return a; }
//!unsigned            bicnv___uint___ulonglong      (unsigned long long  a) { return a; }

//-- long

long                bicnv___slong___sint          (int                 a) { return a; }
long                bicnv___slong___uint          (unsigned            a) { return a; }
long                bicnv___slong___ulong         (unsigned long       a) { return a; }
//!long                bicnv___slong___slonglong     (long long           a) { return a; }
//!long                bicnv___slong___ulonglong     (unsigned long long  a) { return a; }

//-- unsigned long

unsigned long       bicnv___ulong___sint          (int                 a) { return a; }
unsigned long       bicnv___ulong___uint          (unsigned            a) { return a; }
unsigned long       bicnv___ulong___slong         (long                a) { return a; }
//!unsigned long       bicnv___ulong___slonglong     (long long           a) { return a; }
//!unsigned long       bicnv___ulong___ulonglong     (unsigned long long  a) { return a; }

//-- long long

//!long long           bicnv___slonglong___sint      (int                 a) { return a; }
//!long long           bicnv___slonglong___uint      (unsigned            a) { return a; }
//!long long           bicnv___slonglong___slong     (long                a) { return a; }
//!long long           bicnv___slonglong___ulong     (unsigned long       a) { return a; }
//!long long           bicnv___slonglong___ulonglong (unsigned long long  a) { return a; }

//-- unsigned long long

//!unsigned long long  bicnv___ulonglong___sint      (int                 a) { return a; }
//!unsigned long long  bicnv___ulonglong___uint      (unsigned            a) { return a; }
//!unsigned long long  bicnv___ulonglong___slong     (long                a) { return a; }
//!unsigned long long  bicnv___ulonglong___ulong     (unsigned long       a) { return a; }
//!unsigned long long  bicnv___ulonglong___slonglong (long long           a) { return a; }

} //extern "C"  (30 functions of which 18 skipped)
