
// File generated by noodle version O-2018.09#f5599cac26#190121, Tue May 28 10:41:29 2024
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// noodle -Pc -B -Iisg +wisg -Iruntime/include -D__tct_patch__=300 -D__chess__ -D__programmers_view__ tmicro

// File: compile_time_constants.c
// Test compile-time constants : size and alignment in default and other suitable memories

extern "C" {

const int szal___sint_PM                          [] =  //  1,  1
    { sizeof(int   chess_storage(PM)                 ), chess_alignof(int   chess_storage(PM)                 ) };
const int szal___sint_DM                          [] =  //  1,  1
    { sizeof(int /*chess_storage(DM)*/               ), chess_alignof(int /*chess_storage(DM)*/               ) };
const int szal___uint_PM                          [] =  //  1,  1
    { sizeof(unsigned   chess_storage(PM)            ), chess_alignof(unsigned   chess_storage(PM)            ) };
const int szal___uint_DM                          [] =  //  1,  1
    { sizeof(unsigned /*chess_storage(DM)*/          ), chess_alignof(unsigned /*chess_storage(DM)*/          ) };
const int szal___slong_PM                         [] =  //  2,  1
    { sizeof(long   chess_storage(PM)                ), chess_alignof(long   chess_storage(PM)                ) };
const int szal___slong_DM                         [] =  //  2,  1
    { sizeof(long /*chess_storage(DM)*/              ), chess_alignof(long /*chess_storage(DM)*/              ) };
const int szal___ulong_PM                         [] =  //  2,  1
    { sizeof(unsigned long   chess_storage(PM)       ), chess_alignof(unsigned long   chess_storage(PM)       ) };
const int szal___ulong_DM                         [] =  //  2,  1
    { sizeof(unsigned long /*chess_storage(DM)*/     ), chess_alignof(unsigned long /*chess_storage(DM)*/     ) };
const int szal___slonglong_PM                     [] =  //  4,  1
    { sizeof(long long   chess_storage(PM)           ), chess_alignof(long long   chess_storage(PM)           ) };
const int szal___slonglong_DM                     [] =  //  4,  1
    { sizeof(long long /*chess_storage(DM)*/         ), chess_alignof(long long /*chess_storage(DM)*/         ) };
const int szal___ulonglong_PM                     [] =  //  4,  1
    { sizeof(unsigned long long   chess_storage(PM)   ), chess_alignof(unsigned long long   chess_storage(PM)   ) };
const int szal___ulonglong_DM                     [] =  //  4,  1
    { sizeof(unsigned long long /*chess_storage(DM)*/ ), chess_alignof(unsigned long long /*chess_storage(DM)*/ ) };
const int szal___Pvoid_PM                         [] =  //  1,  1
    { sizeof(void *   chess_storage(PM)              ), chess_alignof(void *   chess_storage(PM)              ) };
const int szal___Pvoid_DM                         [] =  //  1,  1
    { sizeof(void * /*chess_storage(DM)*/            ), chess_alignof(void * /*chess_storage(DM)*/            ) };

} //extern "C"  (14 functions)
