
; File generated by darts version O-2018.09#f5599cac26#190121, Tue May 28 10:41:52 2024
; Copyright 2014-2018 Synopsys, Inc. All rights reserved.
; darts -B -I.. +p -d -h -I../runtime/include -D__tct_patch__=300 +Ihex lib/Release/atexit.o tmicro

; Release: ipd O-2018.09-SP3
.data_segment_name
.bss local 1 __atexit_atexits DM 128

.data_segment_name
.data local 1 __atexit_atexit_nxt DM
.rela 8 __atexit_atexits 0
	0x0

.undef local data __atexit_atexit_nxt

.undef local data __atexit_atexits

.undef local data __atexit_atexit_nxt

.undef local data __atexit_atexits

.text_segment_name
.text global 0 __cxa_atexit
	/*      0 0x2413 */    mvi r3,__atexit_atexit_nxt
	/*      1 0x0000 */    /* MW */
	/*      2 0x40c4 */    ld r4,dm(r3)
	/*      3 0x2410 */    mvi r0,__atexit_atexits + 128
	/*      4 0x0080 */    /* MW */
	/*      5 0x1a20 */    eq r4,r0
	/*      6 0x2f04 */    jcr 4
	/*      7 0x4311 */    st r1,dm(r4++)
	/*      8 0x4312 */    st r2,dm(r4++)
	/*      9 0x2ec0 */    rtd 
	/*     10 0x42c4 */    st r4,dm(r3)
	/*     11 0x3000 */    mvib r0,0
	/*     12 0x2ec0 */    rtd 
	/*     13 0x3ff0 */    mvib r0,-1
.label __cxa_atexit__end
	/*     14 0x2e00 */    nop 

.text_segment_name
.text global 0 __cxa_finalize
	/*      0 0x5010 */    addb sp, 1
	/*      1 0x2411 */    mvi r1,__atexit_atexits
	/*      2 0x0000 */    /* MW */
	/*      3 0x2c0c */    jrd 12
	/*      4 0x7ffb */    st lr,dm(sp-1)
	/*      5 0x4001 */    ld r1,dm(r0)
	/*      6 0x3fe2 */    mvib r2,-2
	/*      7 0x004a */    add r1,r1,r2
	/*      8 0x4201 */    st r1,dm(r0)
	/*      9 0x2e00 */    nop 
	/*     10 0x4052 */    ld r2,dm(r1++)
	/*     11 0x2ea2 */    clid r2
	/*     12 0x4040 */    ld r0,dm(r1)
	/*     13 0x2e00 */    nop 
	/*     14 0x2411 */    mvi r1,__atexit_atexits
	/*     15 0x0000 */    /* MW */
.label __ll1___cxa_finalize
	/*     16 0x2410 */    mvi r0,__atexit_atexit_nxt
	/*     17 0x0000 */    /* MW */
	/*     18 0x4002 */    ld r2,dm(r0)
	/*     19 0x1a51 */    ne r2,r1
	/*     20 0x2fef */    jcr -17
	/*     21 0x6ffb */    ld lr,dm(sp-1)
	/*     22 0x2ec0 */    rtd 
	/*     23 0x5ff0 */    addb sp, -1
.label __cxa_finalize__end
	/*     24 0x2e00 */    nop 

