
; File generated by darts version O-2018.09#f5599cac26#190121, Tue May 28 10:41:37 2024
; Copyright 2014-2018 Synopsys, Inc. All rights reserved.
; darts -B -I.. +p -d -h -I../runtime/include -D__tct_patch__=300 +Ihex lib/Release/errno.o tmicro

; Release: ipd O-2018.09-SP3
.data_segment_name
.bss global 1 errno DM 1

