
; File generated by darts version O-2018.09#f5599cac26#190121, Tue May 28 10:41:49 2024
; Copyright 2014-2018 Synopsys, Inc. All rights reserved.
; darts -B -I.. +p -d -h -I../runtime/include -D__tct_patch__=300 +Ihex lib/Release/strtoul.o tmicro

; Release: ipd O-2018.09-SP3
.undef global data _ct_code

.undef global data errno

.text_segment_name
.text global 0 strtoul
	/*      0 0x5150 */    addb sp, 21
	/*      1 0x7fb3 */    st r3,dm(sp-5)
	/*      2 0x7fd2 */    st r2,dm(sp-3)
	/*      3 0x7fcb */    st lr,dm(sp-4)
	/*      4 0x3000 */    mvib r0,0
	/*      5 0x2413 */    mvi r3,256
	/*      6 0x0100 */    /* MW */
	/*      7 0x2415 */    mvi r5,_ct_code
	/*      8 0x0000 */    /* MW */
	/*      9 0x3407 */    mvib r7,64
	/*     10 0x4091 */    ld r1,dm(r2++)
	/*     11 0x0fcb */    geu r1,r3
	/*     12 0x3006 */    mvib r6,0
	/*     13 0x2f03 */    jcr 3
	/*     14 0x018d */    add r6,r1,r5
	/*     15 0x2e00 */    nop 
	/*     16 0x4186 */    ld r6,dm(r6)
	/*     17 0x09b7 */    and r6,r6,r7
	/*     18 0x1a70 */    ne r6,r0
	/*     19 0x2ff5 */    jcr -11
	/*     20 0x2552 */    mv r5,r2
	/*     21 0x4093 */    ld r3,dm(r2++)
	/*     22 0x7f92 */    st r2,dm(sp-7)
	/*     23 0x32d7 */    mvib r7,45
	/*     24 0x1a0f */    eq r1,r7
	/*     25 0x7fa3 */    st r3,dm(sp-6)
	/*     26 0x3012 */    mvib r2,1
	/*     27 0x2f08 */    jcr 8
	/*     28 0x32b2 */    mvib r2,43
	/*     29 0x1a4a */    ne r1,r2
	/*     30 0x2f01 */    jcr 1
	/*     31 0x6f95 */    ld r5,dm(sp-7)
	/*     32 0x2513 */    mv r1,r3
	/*     33 0x7f95 */    st r5,dm(sp-7)
	/*     34 0x7fa1 */    st r1,dm(sp-6)
	/*     35 0x2531 */    mv r3,r1
	/*     36 0x3002 */    mvib r2,0
	/*     37 0x1a20 */    eq r4,r0
	/*     38 0x7f82 */    st r2,dm(sp-8)
	/*     39 0x2f02 */    jcr 2
	/*     40 0x3102 */    mvib r2,16
	/*     41 0x1a62 */    ne r4,r2
	/*     42 0x2f10 */    jcr 16
	/*     43 0x3302 */    mvib r2,48
	/*     44 0x1a5a */    ne r3,r2
	/*     45 0x2f0d */    jcr 13
	/*     46 0x6f91 */    ld r1,dm(sp-7)
	/*     47 0x3782 */    mvib r2,120
	/*     48 0x4041 */    ld r1,dm(r1)
	/*     49 0x1a0a */    eq r1,r2
	/*     50 0x2f02 */    jcr 2
	/*     51 0x3582 */    mvib r2,88
	/*     52 0x1a4a */    ne r1,r2
	/*     53 0x2f05 */    jcr 5
	/*     54 0x6f92 */    ld r2,dm(sp-7)
	/*     55 0x3104 */    mvib r4,16
	/*     56 0x4091 */    ld r1,dm(r2++)
	/*     57 0x4093 */    ld r3,dm(r2++)
	/*     58 0x7f92 */    st r2,dm(sp-7)
	/*     59 0x7fa3 */    st r3,dm(sp-6)
	/*     60 0x3302 */    mvib r2,48
	/*     61 0x1a1a */    eq r3,r2
	/*     62 0x3082 */    mvib r2,8
	/*     63 0x30a1 */    mvib r1,10
	/*     64 0x2291 */    sel r2,r2,r1
	/*     65 0x1a20 */    eq r4,r0
	/*     66 0x2314 */    sel r4,r2,r4
	/*     67 0x174c */    xs r5,r4
	/*     68 0x7f75 */    st r5,dm(sp-9)
	/*     69 0x7f64 */    st r4,dm(sp-10)
	/*     70 0x3ff3 */    mvib r3,-1
	/*     71 0x3ff2 */    mvib r2,-1
	/*     72 0x2e98 */    cl __ulong_div_called___ulong___ulong_R__ulong
	/*     73 0x0000 */    /* MW */
	/*     74 0x7f00 */    st r0,dm(sp-16)
	/*     75 0x3003 */    mvib r3,0
	/*     76 0x7f41 */    st r1,dm(sp-12)
	/*     77 0x7f13 */    st r3,dm(sp-15)
	/*     78 0x7f53 */    st r3,dm(sp-11)
	/*     79 0x7ec3 */    st r3,dm(sp-20)
	/*     80 0x7ef3 */    st r3,dm(sp-17)
	/*     81 0x7eb3 */    st r3,dm(sp-21)
	/*     82 0x7ee3 */    st r3,dm(sp-18)
	/*     83 0x7f33 */    st r3,dm(sp-13)
	/*     84 0x7ed3 */    st r3,dm(sp-19)
	/*     85 0x7f23 */    st r3,dm(sp-14)
	/*     86 0x2414 */    mvi r4,256
	/*     87 0x0100 */    /* MW */
	/*     88 0x6fa5 */    ld r5,dm(sp-6)
	/*     89 0x6f90 */    ld r0,dm(sp-7)
	/*     90 0x2412 */    mvi r2,_ct_code
	/*     91 0x0000 */    /* MW */
	/*     92 0x3571 */    mvib r1,87
	/*     93 0x322b */    mvib lr,34
	/*     94 0x01d5 */    add r7,r2,r5
	/*     95 0x3046 */    mvib r6,4
	/*     96 0x41c7 */    ld r7,dm(r7)
	/*     97 0x09b7 */    and r6,r6,r7
	/*     98 0x0e6c */    ltu r5,r4
	/*     99 0x23b3 */    sel r6,r6,r3
	/*    100 0x1a73 */    ne r6,r3
	/*    101 0x3036 */    mvib r6,3
	/*    102 0x2f0e */    jcr 14
	/*    103 0x09b7 */    and r6,r6,r7
	/*    104 0x0e6c */    ltu r5,r4
	/*    105 0x23b3 */    sel r6,r6,r3
	/*    106 0x1a33 */    eq r6,r3
	/*    107 0x3026 */    mvib r6,2
	/*    108 0x2f4b */    jcr 75
	/*    109 0x09f7 */    and r7,r6,r7
	/*    110 0x0e6c */    ltu r5,r4
	/*    111 0x23fb */    sel r7,r7,r3
	/*    112 0x1a7b */    ne r7,r3
	/*    113 0x3377 */    mvib r7,55
	/*    114 0x23f9 */    sel r7,r7,r1
	/*    115 0x056f */    sub r5,r5,r7
	/*    116 0x2c04 */    jrd 4
	/*    117 0x6f67 */    ld r7,dm(sp-10)
	/*    118 0x3d07 */    mvib r7,-48
	/*    119 0x016f */    add r5,r5,r7
	/*    120 0x6f67 */    ld r7,dm(sp-10)
	/*    121 0x0faf */    ge r5,r7
	/*    122 0x6f27 */    ld r7,dm(sp-14)
	/*    123 0x2f3c */    jcr 60
	/*    124 0x0e3b */    lt r7,r3
	/*    125 0x2f38 */    jcr 56
	/*    126 0x6ec1 */    ld r1,dm(sp-20)
	/*    127 0x6f43 */    ld r3,dm(sp-12)
	/*    128 0x0e59 */    ltu r3,r1
	/*    129 0x6f61 */    ld r1,dm(sp-10)
	/*    130 0x7fa0 */    st r0,dm(sp-6)
	/*    131 0x2f20 */    jcr 32
	/*    132 0x6f43 */    ld r3,dm(sp-12)
	/*    133 0x6ec0 */    ld r0,dm(sp-20)
	/*    134 0x1a58 */    ne r3,r0
	/*    135 0x2f03 */    jcr 3
	/*    136 0x6ef0 */    ld r0,dm(sp-17)
	/*    137 0x6f03 */    ld r3,dm(sp-16)
	/*    138 0x0e58 */    ltu r3,r0
	/*    139 0x2f18 */    jcr 24
	/*    140 0x6eb0 */    ld r0,dm(sp-21)
	/*    141 0x6f43 */    ld r3,dm(sp-12)
	/*    142 0x1a43 */    ne r0,r3
	/*    143 0x2f06 */    jcr 6
	/*    144 0x6ee0 */    ld r0,dm(sp-18)
	/*    145 0x6f03 */    ld r3,dm(sp-16)
	/*    146 0x1a43 */    ne r0,r3
	/*    147 0x2f02 */    jcr 2
	/*    148 0x6fe0 */    ld r0,dm(sp-2)
	/*    149 0x0f28 */    gt r5,r0
	/*    150 0x2f0d */    jcr 13
	/*    151 0x6ee0 */    ld r0,dm(sp-18)
	/*    152 0x3013 */    mvib r3,1
	/*    153 0x1841 */    muluu (r6,r7),r0,r1
	/*    154 0x7f23 */    st r3,dm(sp-14)
	/*    155 0x00ee */    add r3,r5,r6
	/*    156 0x6eb6 */    ld r6,dm(sp-21)
	/*    157 0x18f1 */    macl (r7),r6,r1
	/*    158 0x6f71 */    ld r1,dm(sp-9)
	/*    159 0x174d */    xs r5,r5
	/*    160 0x18c8 */    macl (r7),r1,r0
	/*    161 0x022f */    addc r0,r5,r7
	/*    162 0x7ed3 */    st r3,dm(sp-19)
	/*    163 0x2c0a */    jrd 10
	/*    164 0x7f30 */    st r0,dm(sp-13)
	/*    165 0x2415 */    mvi r5,errno
	/*    166 0x0000 */    /* MW */
	/*    167 0x3ff1 */    mvib r1,-1
	/*    168 0x3ff3 */    mvib r3,-1
	/*    169 0x3ff0 */    mvib r0,-1
	/*    170 0x7f30 */    st r0,dm(sp-13)
	/*    171 0x434b */    st lr,dm(r5)
	/*    172 0x7ed3 */    st r3,dm(sp-19)
	/*    173 0x7f21 */    st r1,dm(sp-14)
	/*    174 0x7ec0 */    st r0,dm(sp-20)
	/*    175 0x7eb0 */    st r0,dm(sp-21)
	/*    176 0x7f10 */    st r0,dm(sp-15)
	/*    177 0x7ef3 */    st r3,dm(sp-17)
	/*    178 0x7ee3 */    st r3,dm(sp-18)
	/*    179 0x7f53 */    st r3,dm(sp-11)
	/*    180 0x3003 */    mvib r3,0
	/*    181 0x6fa0 */    ld r0,dm(sp-6)
	/*    182 0x3571 */    mvib r1,87
	/*    183 0x2ca6 */    jrd -90
	/*    184 0x4015 */    ld r5,dm(r0++)
.label __ll2_strtoul
	/*    185 0x6f84 */    ld r4,dm(sp-8)
	/*    186 0x1a23 */    eq r4,r3
	/*    187 0x6fb4 */    ld r4,dm(sp-5)
	/*    188 0x2f08 */    jcr 8
	/*    189 0x6f22 */    ld r2,dm(sp-14)
	/*    190 0x0e93 */    le r2,r3
	/*    191 0x2f05 */    jcr 5
	/*    192 0x6f52 */    ld r2,dm(sp-11)
	/*    193 0x049a */    sub r2,r3,r2
	/*    194 0x6f11 */    ld r1,dm(sp-15)
	/*    195 0x0659 */    subb r1,r3,r1
	/*    196 0x7f31 */    st r1,dm(sp-13)
	/*    197 0x7ed2 */    st r2,dm(sp-19)
	/*    198 0x3002 */    mvib r2,0
	/*    199 0x1a22 */    eq r4,r2
	/*    200 0x6f22 */    ld r2,dm(sp-14)
	/*    201 0x2f05 */    jcr 5
	/*    202 0x1a13 */    eq r2,r3
	/*    203 0x6fd2 */    ld r2,dm(sp-3)
	/*    204 0x2f01 */    jcr 1
	/*    205 0x4022 */    ld r2,dm(r0--)
	/*    206 0x2520 */    mv r2,r0
	/*    207 0x4302 */    st r2,dm(r4)
	/*    208 0x2e00 */    nop 
	/*    209 0x6f31 */    ld r1,dm(sp-13)
	/*    210 0x6fcb */    ld lr,dm(sp-4)
	/*    211 0x2ec0 */    rtd 
	/*    212 0x6ed0 */    ld r0,dm(sp-19)
.label strtoul__end
	/*    213 0x5eb0 */    addb sp, -21

.undef global text __ulong_div_called___ulong___ulong_R__ulong

.undef global data _ct_code

.undef global data errno

