
; File generated by darts version O-2018.09#f5599cac26#190121, Tue May 28 10:41:48 2024
; Copyright 2014-2018 Synopsys, Inc. All rights reserved.
; darts -B -I.. +p -d -h -I../runtime/include -D__tct_patch__=300 +Ihex lib/Release/strtol.o tmicro

; Release: ipd O-2018.09-SP3
.undef global data _ct_code

.undef global data errno

.text_segment_name
.text global 0 strtol
	/*      0 0x5130 */    addb sp, 19
	/*      1 0x7fb3 */    st r3,dm(sp-5)
	/*      2 0x7fd2 */    st r2,dm(sp-3)
	/*      3 0x7fcb */    st lr,dm(sp-4)
	/*      4 0x3000 */    mvib r0,0
	/*      5 0x2415 */    mvi r5,256
	/*      6 0x0100 */    /* MW */
	/*      7 0x2413 */    mvi r3,_ct_code
	/*      8 0x0000 */    /* MW */
	/*      9 0x3407 */    mvib r7,64
	/*     10 0x4091 */    ld r1,dm(r2++)
	/*     11 0x0fcd */    geu r1,r5
	/*     12 0x3006 */    mvib r6,0
	/*     13 0x2f03 */    jcr 3
	/*     14 0x018b */    add r6,r1,r3
	/*     15 0x2e00 */    nop 
	/*     16 0x4186 */    ld r6,dm(r6)
	/*     17 0x09b7 */    and r6,r6,r7
	/*     18 0x1a70 */    ne r6,r0
	/*     19 0x2ff5 */    jcr -11
	/*     20 0x2532 */    mv r3,r2
	/*     21 0x4095 */    ld r5,dm(r2++)
	/*     22 0x7f92 */    st r2,dm(sp-7)
	/*     23 0x32d7 */    mvib r7,45
	/*     24 0x1a0f */    eq r1,r7
	/*     25 0x7fa5 */    st r5,dm(sp-6)
	/*     26 0x3012 */    mvib r2,1
	/*     27 0x2f08 */    jcr 8
	/*     28 0x32b2 */    mvib r2,43
	/*     29 0x1a4a */    ne r1,r2
	/*     30 0x2f01 */    jcr 1
	/*     31 0x6f93 */    ld r3,dm(sp-7)
	/*     32 0x2515 */    mv r1,r5
	/*     33 0x7f93 */    st r3,dm(sp-7)
	/*     34 0x7fa1 */    st r1,dm(sp-6)
	/*     35 0x2551 */    mv r5,r1
	/*     36 0x3002 */    mvib r2,0
	/*     37 0x1a20 */    eq r4,r0
	/*     38 0x7f82 */    st r2,dm(sp-8)
	/*     39 0x2f02 */    jcr 2
	/*     40 0x3101 */    mvib r1,16
	/*     41 0x1a61 */    ne r4,r1
	/*     42 0x2f10 */    jcr 16
	/*     43 0x3301 */    mvib r1,48
	/*     44 0x1a69 */    ne r5,r1
	/*     45 0x2f0d */    jcr 13
	/*     46 0x6f93 */    ld r3,dm(sp-7)
	/*     47 0x3781 */    mvib r1,120
	/*     48 0x40c3 */    ld r3,dm(r3)
	/*     49 0x1a19 */    eq r3,r1
	/*     50 0x2f02 */    jcr 2
	/*     51 0x3581 */    mvib r1,88
	/*     52 0x1a59 */    ne r3,r1
	/*     53 0x2f05 */    jcr 5
	/*     54 0x6f91 */    ld r1,dm(sp-7)
	/*     55 0x3104 */    mvib r4,16
	/*     56 0x4055 */    ld r5,dm(r1++)
	/*     57 0x4055 */    ld r5,dm(r1++)
	/*     58 0x7f91 */    st r1,dm(sp-7)
	/*     59 0x7fa5 */    st r5,dm(sp-6)
	/*     60 0x3301 */    mvib r1,48
	/*     61 0x1a29 */    eq r5,r1
	/*     62 0x3081 */    mvib r1,8
	/*     63 0x30a5 */    mvib r5,10
	/*     64 0x224d */    sel r1,r1,r5
	/*     65 0x1a20 */    eq r4,r0
	/*     66 0x230c */    sel r4,r1,r4
	/*     67 0x1a50 */    ne r2,r0
	/*     68 0x3ff2 */    mvib r2,-1
	/*     69 0x2282 */    sel r2,r0,r2
	/*     70 0x174c */    xs r5,r4
	/*     71 0x2410 */    mvi r0,-32768
	/*     72 0x8000 */    /* MW */
	/*     73 0x2411 */    mvi r1,32767
	/*     74 0x7fff */    /* MW */
	/*     75 0x22c1 */    sel r3,r0,r1
	/*     76 0x7f75 */    st r5,dm(sp-9)
	/*     77 0x7f64 */    st r4,dm(sp-10)
	/*     78 0x2e98 */    cl __slong_div_called___slong___slong_R__slong
	/*     79 0x0000 */    /* MW */
	/*     80 0x6f84 */    ld r4,dm(sp-8)
	/*     81 0x3005 */    mvib r5,0
	/*     82 0x1a25 */    eq r4,r5
	/*     83 0x7f51 */    st r1,dm(sp-11)
	/*     84 0x7f40 */    st r0,dm(sp-12)
	/*     85 0x2f0d */    jcr 13
	/*     86 0x6fe4 */    ld r4,dm(sp-2)
	/*     87 0x0ea5 */    le r4,r5
	/*     88 0x2f08 */    jcr 8
	/*     89 0x6f42 */    ld r2,dm(sp-12)
	/*     90 0x3010 */    mvib r0,1
	/*     91 0x0082 */    add r2,r0,r2
	/*     92 0x6f50 */    ld r0,dm(sp-11)
	/*     93 0x0205 */    addc r0,r0,r5
	/*     94 0x6f61 */    ld r1,dm(sp-10)
	/*     95 0x0521 */    sub r4,r4,r1
	/*     96 0x7f50 */    st r0,dm(sp-11)
	/*     97 0x7f42 */    st r2,dm(sp-12)
	/*     98 0x052c */    sub r4,r5,r4
	/*     99 0x7fe4 */    st r4,dm(sp-2)
	/*    100 0x7ef5 */    st r5,dm(sp-17)
	/*    101 0x7ee5 */    st r5,dm(sp-18)
	/*    102 0x7f15 */    st r5,dm(sp-15)
	/*    103 0x7ed5 */    st r5,dm(sp-19)
	/*    104 0x7f05 */    st r5,dm(sp-16)
	/*    105 0x7f35 */    st r5,dm(sp-13)
	/*    106 0x7f25 */    st r5,dm(sp-14)
	/*    107 0x2412 */    mvi r2,256
	/*    108 0x0100 */    /* MW */
	/*    109 0x6fa3 */    ld r3,dm(sp-6)
	/*    110 0x6f94 */    ld r4,dm(sp-7)
	/*    111 0x2410 */    mvi r0,_ct_code
	/*    112 0x0000 */    /* MW */
	/*    113 0x3571 */    mvib r1,87
	/*    114 0x322b */    mvib lr,34
.label TGT_Fstrtol_115
	/*    115 0x01c3 */    add r7,r0,r3
	/*    116 0x3046 */    mvib r6,4
	/*    117 0x41c7 */    ld r7,dm(r7)
	/*    118 0x09b7 */    and r6,r6,r7
	/*    119 0x0e5a */    ltu r3,r2
	/*    120 0x23b5 */    sel r6,r6,r5
	/*    121 0x1a75 */    ne r6,r5
	/*    122 0x3036 */    mvib r6,3
	/*    123 0x2f0f */    jcr 15
	/*    124 0x09b7 */    and r6,r6,r7
	/*    125 0x0e5a */    ltu r3,r2
	/*    126 0x23b5 */    sel r6,r6,r5
	/*    127 0x1a35 */    eq r6,r5
	/*    128 0x3026 */    mvib r6,2
	/*    129 0x2e90 */    jc __ll2_strtol
	/*    130 0x0104 */    /* MW */
	/*    131 0x09f7 */    and r7,r6,r7
	/*    132 0x0e5a */    ltu r3,r2
	/*    133 0x23fd */    sel r7,r7,r5
	/*    134 0x1a7d */    ne r7,r5
	/*    135 0x3377 */    mvib r7,55
	/*    136 0x23f9 */    sel r7,r7,r1
	/*    137 0x04df */    sub r3,r3,r7
	/*    138 0x2c04 */    jrd 4
	/*    139 0x6f67 */    ld r7,dm(sp-10)
	/*    140 0x3d07 */    mvib r7,-48
	/*    141 0x00df */    add r3,r3,r7
	/*    142 0x6f67 */    ld r7,dm(sp-10)
	/*    143 0x0f9f */    ge r3,r7
	/*    144 0x6f27 */    ld r7,dm(sp-14)
	/*    145 0x2f71 */    jcr 113
	/*    146 0x0e3d */    lt r7,r5
	/*    147 0x2f6c */    jcr 108
	/*    148 0x6ed1 */    ld r1,dm(sp-19)
	/*    149 0x6f65 */    ld r5,dm(sp-10)
	/*    150 0x184d */    muluu (r6,r7),r1,r5
	/*    151 0x7fa6 */    st r6,dm(sp-6)
	/*    152 0x2e00 */    nop 
	/*    153 0x6f16 */    ld r6,dm(sp-15)
	/*    154 0x18f5 */    macl (r7),r6,r5
	/*    155 0x6f75 */    ld r5,dm(sp-9)
	/*    156 0x18e9 */    macl (r7),r5,r1
	/*    157 0x6f51 */    ld r1,dm(sp-11)
	/*    158 0x1a71 */    ne r6,r1
	/*    159 0x3011 */    mvib r1,1
	/*    160 0x7f31 */    st r1,dm(sp-13)
	/*    161 0x7f97 */    st r7,dm(sp-7)
	/*    162 0x164b */    xs r1,r3
	/*    163 0x3005 */    mvib r5,0
	/*    164 0x2f06 */    jcr 6
	/*    165 0x6f46 */    ld r6,dm(sp-12)
	/*    166 0x6ed7 */    ld r7,dm(sp-19)
	/*    167 0x1a7e */    ne r7,r6
	/*    168 0x3017 */    mvib r7,1
	/*    169 0x2f00 */    jcr 0
	/*    170 0x3007 */    mvib r7,0
	/*    171 0x7f37 */    st r7,dm(sp-13)
	/*    172 0x2e00 */    nop 
	/*    173 0x6f87 */    ld r7,dm(sp-8)
	/*    174 0x1a7d */    ne r7,r5
	/*    175 0x2f25 */    jcr 37
	/*    176 0x6ef6 */    ld r6,dm(sp-17)
	/*    177 0x6f57 */    ld r7,dm(sp-11)
	/*    178 0x0e3e */    lt r7,r6
	/*    179 0x3017 */    mvib r7,1
	/*    180 0x2f16 */    jcr 22
	/*    181 0x6f55 */    ld r5,dm(sp-11)
	/*    182 0x1a6e */    ne r5,r6
	/*    183 0x3005 */    mvib r5,0
	/*    184 0x2f04 */    jcr 4
	/*    185 0x6ee5 */    ld r5,dm(sp-18)
	/*    186 0x6f46 */    ld r6,dm(sp-12)
	/*    187 0x0e75 */    ltu r6,r5
	/*    188 0x3005 */    mvib r5,0
	/*    189 0x2f0d */    jcr 13
	/*    190 0x6f36 */    ld r6,dm(sp-13)
	/*    191 0x1a75 */    ne r6,r5
	/*    192 0x2f02 */    jcr 2
	/*    193 0x6fe6 */    ld r6,dm(sp-2)
	/*    194 0x0f1e */    gt r3,r6
	/*    195 0x2f07 */    jcr 7
	/*    196 0x6fa6 */    ld r6,dm(sp-6)
	/*    197 0x7f27 */    st r7,dm(sp-14)
	/*    198 0x00de */    add r3,r3,r6
	/*    199 0x6f97 */    ld r7,dm(sp-7)
	/*    200 0x024f */    addc r1,r1,r7
	/*    201 0x7f33 */    st r3,dm(sp-13)
	/*    202 0x2c31 */    jrd 49
	/*    203 0x7f01 */    st r1,dm(sp-16)
	/*    204 0x3ff3 */    mvib r3,-1
	/*    205 0x2411 */    mvi r1,32767
	/*    206 0x7fff */    /* MW */
	/*    207 0x7f01 */    st r1,dm(sp-16)
	/*    208 0x7f33 */    st r3,dm(sp-13)
	/*    209 0x7f23 */    st r3,dm(sp-14)
	/*    210 0x2417 */    mvi r7,errno
	/*    211 0x0000 */    /* MW */
	/*    212 0x2c27 */    jrd 39
	/*    213 0x43cb */    st lr,dm(r7)
	/*    214 0x6f16 */    ld r6,dm(sp-15)
	/*    215 0x6f57 */    ld r7,dm(sp-11)
	/*    216 0x0e37 */    lt r6,r7
	/*    217 0x6fa7 */    ld r7,dm(sp-6)
	/*    218 0x2f16 */    jcr 22
	/*    219 0x6f55 */    ld r5,dm(sp-11)
	/*    220 0x1a75 */    ne r6,r5
	/*    221 0x3005 */    mvib r5,0
	/*    222 0x2f04 */    jcr 4
	/*    223 0x6f45 */    ld r5,dm(sp-12)
	/*    224 0x6ed6 */    ld r6,dm(sp-19)
	/*    225 0x0e75 */    ltu r6,r5
	/*    226 0x3005 */    mvib r5,0
	/*    227 0x2f0d */    jcr 13
	/*    228 0x6f36 */    ld r6,dm(sp-13)
	/*    229 0x1a75 */    ne r6,r5
	/*    230 0x2f02 */    jcr 2
	/*    231 0x6fe6 */    ld r6,dm(sp-2)
	/*    232 0x0f1e */    gt r3,r6
	/*    233 0x2f07 */    jcr 7
	/*    234 0x04fb */    sub r3,r7,r3
	/*    235 0x6f97 */    ld r7,dm(sp-7)
	/*    236 0x0679 */    subb r1,r7,r1
	/*    237 0x7f01 */    st r1,dm(sp-16)
	/*    238 0x7f33 */    st r3,dm(sp-13)
	/*    239 0x3017 */    mvib r7,1
	/*    240 0x2c0b */    jrd 11
	/*    241 0x7f27 */    st r7,dm(sp-14)
	/*    242 0x3ff3 */    mvib r3,-1
	/*    243 0x2417 */    mvi r7,errno
	/*    244 0x0000 */    /* MW */
	/*    245 0x7f23 */    st r3,dm(sp-14)
	/*    246 0x2411 */    mvi r1,-32768
	/*    247 0x8000 */    /* MW */
	/*    248 0x43cb */    st lr,dm(r7)
	/*    249 0x7f01 */    st r1,dm(sp-16)
	/*    250 0x7f35 */    st r5,dm(sp-13)
	/*    251 0x3003 */    mvib r3,0
	/*    252 0x7f11 */    st r1,dm(sp-15)
	/*    253 0x7ef1 */    st r1,dm(sp-17)
	/*    254 0x7ee3 */    st r3,dm(sp-18)
	/*    255 0x7ed3 */    st r3,dm(sp-19)
	/*    256 0x3571 */    mvib r1,87
	/*    257 0x4113 */    ld r3,dm(r4++)
	/*    258 0x2e80 */    j TGT_Fstrtol_115
	/*    259 0x0073 */    /* MW */
.label __ll2_strtol
	/*    260 0x6fb2 */    ld r2,dm(sp-5)
	/*    261 0x3000 */    mvib r0,0
	/*    262 0x1a10 */    eq r2,r0
	/*    263 0x6f20 */    ld r0,dm(sp-14)
	/*    264 0x2f05 */    jcr 5
	/*    265 0x1a05 */    eq r0,r5
	/*    266 0x6fd0 */    ld r0,dm(sp-3)
	/*    267 0x2f01 */    jcr 1
	/*    268 0x4120 */    ld r0,dm(r4--)
	/*    269 0x2504 */    mv r0,r4
	/*    270 0x4280 */    st r0,dm(r2)
	/*    271 0x2e00 */    nop 
	/*    272 0x6f01 */    ld r1,dm(sp-16)
	/*    273 0x6fcb */    ld lr,dm(sp-4)
	/*    274 0x2ec0 */    rtd 
	/*    275 0x6f30 */    ld r0,dm(sp-13)
.label strtol__end
	/*    276 0x5ed0 */    addb sp, -19

.undef global text __slong_div_called___slong___slong_R__slong

.undef global data _ct_code

.undef global data errno

