
// File generated by Go version O-2018.09#f5599cac26#190121, Tue May 28 10:45:21 2024
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// go -B -I../lib -F -D__tct_patch__=300 -Verilog -otmicro_vlog -cgo_options.cfg -Itmicro_vlog/tmp_pdg -updg -updg_controller tmicro



`timescale 1ns/1ps

// module mux1 : mux_mulx mux_muly
module mux1
  ( input              [1:0] bin_selector_E1,
    input      signed [15:0] in0, // word mulx1 muly1
    input      signed [15:0] in1, // word mulx2 muly2
    output reg signed [15:0] out0 // word mulx muly
  );


  always @ (*)

  begin : p_mux1


    reg    signed [15:0] in0_opd; // word
    reg    signed [15:0] in1_opd; // word

    out0 = 0; // 1:mulx 2:muly

    // operand isolation
    if (bin_selector_E1 == 0)
    begin
      in0_opd = 0;
      in1_opd = 0;
    end
    else
    begin
      in0_opd = in0;
      in1_opd = in1;
    end


    case (bin_selector_E1)
      2'b01 : // 1:(mulx_copy_mulx1_E1)
              // 2:(muly_copy_muly1_E1)
      begin
        // [alu.n:232]
        out0 = in0_opd;
      end
      2'b10 : // 1:(mulx_copy_mulx2_E1)
              // 2:(muly_copy_muly2_E1)
      begin
        // [alu.n:218][alu.n:219]
        out0 = in1_opd;
      end
      default :
        ; // null
    endcase

  end

endmodule
