
// File generated by Go version O-2018.09#f5599cac26#190121, Tue May 28 10:45:21 2024
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// go -B -I../lib -F -D__tct_patch__=300 -Verilog -otmicro_vlog -cgo_options.cfg -Itmicro_vlog/tmp_pdg -updg -updg_controller tmicro



`timescale 1ns/1ps

// module mux3 : mux_die1 mux_jcr mux_jc
module mux3
  ( input      ohe_selector_E1,
    output reg out0 // bool die1 jcr jc
  );


  always @ (*)

  begin : p_mux3

    out0 = 1'b0; // hw_init // 1:die1 2:jcr 3:jc


    if (ohe_selector_E1) // 1:(die1_copy0___CTbool_cstV1_E1)
                         // 2:(jcr_copy0___CTbool_cstV1_E1)
                         // 3:(jc_copy0___CTbool_cstV1_E1)
    begin
      // [move.n:86][control.n:94][control.n:144][control.n:162][control.n:223][control.n:252]
      out0 = 1'b1;
    end

  end

endmodule
