
// File generated by Go version O-2018.09#f5599cac26#190121, Tue May 28 10:45:21 2024
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// go -B -I../lib -F -D__tct_patch__=300 -Verilog -otmicro_vlog -cgo_options.cfg -Itmicro_vlog/tmp_pdg -updg -updg_controller tmicro



`timescale 1ns/1ps

// module mux_pm_addr : mux_pm_addr
module mux_pm_addr
  ( input                    ohe_selector_E1,
    input                    ohe_selector_ID,
    input                    __ocd_st_PME1_r_in, // bool
    input                    ocd_ld_PM_in, // bool
    input                    pm_ld_pdg_en_in, // std_logic
    input             [15:0] __pm_addr_pipe_r_in, // addr
    input      signed [15:0] ag1p_in, // word
    input             [15:0] ocd_addr_r_in, // addr
    input             [15:0] pm_addr1_in, // addr
    output reg        [15:0] pm_addr_out // addr
  );


  always @ (*)

  begin : p_mux_pm_addr


    reg    signed [15:0] ag1p; // word

    pm_addr_out = 0;

    // operand isolation
    if (ohe_selector_ID == 0)
    begin
      ag1p = 0;
    end
    else
    begin
      ag1p = ag1p_in;
    end


    // (pm_addr_copy0_pm_addr_pipe___ocd_st_PME1_r_E1_alw, pm_addr_copy0_ocd_addr_r_ocd_ld_PM_ID_alw, pm_addr_copy_pm_addr1_pm_ld_pdg_en)
    if (__ocd_st_PME1_r_in)
    begin
      // [ocd_if.n:46]
      pm_addr_out = __pm_addr_pipe_r_in;
    end
    if (ocd_ld_PM_in)
    begin
      // [ocd_if.n:40]
      pm_addr_out = ocd_addr_r_in;
    end
    if (pm_ld_pdg_en_in)
    begin
      pm_addr_out = pm_addr1_in;
    end

    if (ohe_selector_E1) // (pm_addr_copy0_pm_addr_pipe_E1)
    begin
      // [load_store.n:129]
      pm_addr_out = __pm_addr_pipe_r_in;
    end

    if (ohe_selector_ID) // (pm_addr_copy0_ag1p_ID)
    begin
      // [load_store.n:115]
      pm_addr_out = $unsigned(ag1p);
    end

  end

endmodule
