
// File generated by Go version O-2018.09#f5599cac26#190121, Tue May 28 10:45:21 2024
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// go -B -I../lib -F -D__tct_patch__=300 -Verilog -otmicro_vlog -cgo_options.cfg -Itmicro_vlog/tmp_pdg -updg -updg_controller tmicro



`timescale 1ns/1ps

// module mux_trgt : mux_trgt
module mux_trgt
  ( input              [1:0] bin_selector_E1,
    input              [1:0] bin_selector_ID,
    input             [15:0] __CTaddr_cstP16_E1_in, // addr
    input             [15:0] __CTaddr_cstP16_ID_in, // addr
    input              [3:0] __CTuint4_cstP12_ID_in, // uint4
    input      signed [15:0] __trgt_r_ILR_in, // word
    input      signed [15:0] __trgt_r_LR_in, // word
    input      signed [15:0] rse1_in, // word
    output reg        [15:0] trgt_out // addr
  );


  always @ (*)

  begin : p_mux_trgt


    reg    [15:0] __CTaddr_cstP16_E1_in_opd; // addr
    reg    [15:0] __CTaddr_cstP16_ID_in_opd; // addr
    reg    [3:0] __CTuint4_cstP12_ID_in_opd; // uint4
    reg    signed [15:0] __trgt_r_ILR; // word
    reg    signed [15:0] __trgt_r_LR; // word
    reg    signed [15:0] rse1; // word

    trgt_out = 16'b0000000000000000; // hw_init

    // operand isolation
    if (bin_selector_E1 == 0)
    begin
      __CTaddr_cstP16_E1_in_opd = 0;
      __trgt_r_LR = 0;
      rse1 = 0;
    end
    else
    begin
      __CTaddr_cstP16_E1_in_opd = __CTaddr_cstP16_E1_in;
      __trgt_r_LR = __trgt_r_LR_in;
      rse1 = rse1_in;
    end
    if (bin_selector_ID == 0)
    begin
      __CTaddr_cstP16_ID_in_opd = 0;
      __CTuint4_cstP12_ID_in_opd = 0;
      __trgt_r_ILR = 0;
    end
    else
    begin
      __CTaddr_cstP16_ID_in_opd = __CTaddr_cstP16_ID_in;
      __CTuint4_cstP12_ID_in_opd = __CTuint4_cstP12_ID_in;
      __trgt_r_ILR = __trgt_r_ILR_in;
    end


    case (bin_selector_E1)
      2'b01 : // (trgt_copy0___CTaddr_cstP16_E1)
      begin
        // [control.n:122]
        trgt_out = __CTaddr_cstP16_E1_in_opd;
      end
      2'b10 : // (trgt_copy0___trgt_r_LR_E1)
      begin
        // [control.n:153][control.n:162]
        trgt_out = $unsigned(__trgt_r_LR);
      end
      2'b11 : // (trgt_copy0_rse1_E1)
      begin
        // [control.n:112][control.n:145](tmicro.n:160)
        trgt_out = $unsigned(rse1);
      end
      default :
        ; // null
    endcase

    case (bin_selector_ID)
      2'b01 : // (trgt_copy0___CTaddr_cstP16_ID)
      begin
        // [control.n:105][control.n:132]
        trgt_out = __CTaddr_cstP16_ID_in_opd;
      end
      2'b10 : // (trgt_copy0___CTuint4_cstP12_ID)
      begin
        // [control.n:220]
        trgt_out = {{12{1'b0}}, __CTuint4_cstP12_ID_in_opd};
      end
      2'b11 : // (trgt_copy0___trgt_r_ILR_ID)
      begin
        // [control.n:235]
        trgt_out = $unsigned(__trgt_r_ILR);
      end
      default :
        ; // null
    endcase

  end

endmodule
