
// File generated by Go version O-2018.09#f5599cac26#190121, Tue May 28 10:45:21 2024
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// go -B -I../lib -F -D__tct_patch__=300 -Verilog -otmicro_vlog -cgo_options.cfg -Itmicro_vlog/tmp_pdg -updg -updg_controller tmicro



`timescale 1ns/1ps

// module mux_rte1 : mux_rte1
module mux_rte1
  ( input              [2:0] bin_selector_E1,
    input      signed [15:0] alut_in, // word
    input      signed [15:0] dm_read_dp_in, // word
    input             [15:0] pm_read_dp_in, // iword
    input      signed [15:0] sht_in, // word
    input      signed [15:0] wbus_in, // word
    output reg signed [15:0] rte1_out // word
  );


  always @ (*)

  begin : p_mux_rte1


    reg    signed [15:0] alut; // word
    reg    signed [15:0] dm_read_dp; // word
    reg    [15:0] pm_read_dp; // iword
    reg    signed [15:0] sht; // word
    reg    signed [15:0] wbus; // word

    rte1_out = 0;

    // operand isolation
    if (bin_selector_E1 == 0)
    begin
      pm_read_dp = 0;
      alut = 0;
      dm_read_dp = 0;
      sht = 0;
      wbus = 0;
    end
    else
    begin
      pm_read_dp = pm_read_dp_in;
      alut = alut_in;
      dm_read_dp = dm_read_dp_in;
      sht = sht_in;
      wbus = wbus_in;
    end


    case (bin_selector_E1)
      3'b001 : // (rte1_copy0_pm_read_E1)
      begin
        // [load_store.n:116](tmicro.n:125)
        rte1_out = $signed(pm_read_dp);
      end
      3'b010 : // (rte1_copy0_alut_E1)
      begin
        // [alu.n:76][alu.n:127][alu.n:143][alu.n:156][alu.n:168](tmicro.n:161)
        rte1_out = alut;
      end
      3'b011 : // (rte1_copy0_dm_read_E1)
      begin
        // [load_store.n:51][load_store.n:93](tmicro.n:125)
        rte1_out = dm_read_dp;
      end
      3'b100 : // (rte1_copy0_sht_E1)
      begin
        // [alu.n:190](tmicro.n:161)
        rte1_out = sht;
      end
      3'b101 : // (rte1_copy0_wbus_E1)
      begin
        // [move.n:48][move.n:55][move.n:62][move.n:106][dma.n:70](tmicro.n:125)
        rte1_out = wbus;
      end
      default :
        ; // null
    endcase

  end

endmodule
