
// File generated by Go version O-2018.09#f5599cac26#190121, Tue May 28 10:45:21 2024
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// go -B -I../lib -F -D__tct_patch__=300 -Verilog -otmicro_vlog -cgo_options.cfg -Itmicro_vlog/tmp_pdg -updg -updg_controller tmicro



`timescale 1ns/1ps

// module mux_lcw : mux_lcw
module mux_lcw
  ( input              [1:0] bin_selector_E1,
    input                    LC_lcw_cntrl_nxtpc_pdg_en_in, // std_logic
    input             [15:0] __CTaddr_cstP32_E1_in, // addr
    input             [15:0] lcw1_in, // addr
    input      signed [15:0] rse1_in, // word
    output reg        [15:0] lcw_out // addr
  );


  always @ (*)

  begin : p_mux_lcw


    reg    [15:0] __CTaddr_cstP32_E1_in_opd; // addr
    reg    signed [15:0] rse1; // word

    lcw_out = 0;

    // operand isolation
    if (bin_selector_E1 == 0)
    begin
      __CTaddr_cstP32_E1_in_opd = 0;
      rse1 = 0;
    end
    else
    begin
      __CTaddr_cstP32_E1_in_opd = __CTaddr_cstP32_E1_in;
      rse1 = rse1_in;
    end


    // (lcw_copy_lcw1_LC_lcw_cntrl_nxtpc_pdg_en)
    if (LC_lcw_cntrl_nxtpc_pdg_en_in)
    begin
      lcw_out = lcw1_in;
    end

    case (bin_selector_E1)
      2'b01 : // (lcw_copy0___CTaddr_cstP32_E1)
      begin
        // [control.n:202]
        lcw_out = __CTaddr_cstP32_E1_in_opd;
      end
      2'b10 : // (lcw_copy0_rse1_E1)
      begin
        // [control.n:191]
        lcw_out = $unsigned(rse1);
      end
      default :
        ; // null
    endcase

  end

endmodule
