
// File generated by Go version O-2018.09#f5599cac26#190121, Tue May 28 10:45:21 2024
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// go -B -I../lib -F -D__tct_patch__=300 -Verilog -otmicro_vlog -cgo_options.cfg -Itmicro_vlog/tmp_pdg -updg -updg_controller tmicro



`timescale 1ns/1ps

// module mux_ag1m : mux_ag1m
module mux_ag1m
  ( input              [2:0] bin_selector_ID,
    input       signed [8:0] __CTnint9_cstP4_7_0_ID_in, // nint9
    input       signed [7:0] __CTsbyte_cstP4_ID_in, // sbyte
    input      signed [15:0] __CTword_cstP16_ID_in, // word
    output reg signed [15:0] ag1m_out // word
  );


  always @ (*)

  begin : p_mux_ag1m


    reg    signed [8:0] __CTnint9_cstP4_7_0_ID_in_opd; // nint9
    reg    signed [7:0] __CTsbyte_cstP4_ID_in_opd; // sbyte
    reg    signed [15:0] __CTword_cstP16_ID_in_opd; // word

    ag1m_out = 0;

    // operand isolation
    if (bin_selector_ID == 0)
    begin
      __CTword_cstP16_ID_in_opd = 0;
      __CTnint9_cstP4_7_0_ID_in_opd = 0;
      __CTsbyte_cstP4_ID_in_opd = 0;
    end
    else
    begin
      __CTword_cstP16_ID_in_opd = __CTword_cstP16_ID_in;
      __CTnint9_cstP4_7_0_ID_in_opd = __CTnint9_cstP4_7_0_ID_in;
      __CTsbyte_cstP4_ID_in_opd = __CTsbyte_cstP4_ID_in;
    end


    case (bin_selector_ID)
      3'b001 : // (ag1m_copy0___CTnint9_cstP4_7_0_ID)
      begin
        // [load_store.n:46]
        ag1m_out = $signed({{7{__CTnint9_cstP4_7_0_ID_in_opd[8]}}, __CTnint9_cstP4_7_0_ID_in_opd});
      end
      3'b010 : // (ag1m_copy0___CTsbyte_cstP4_ID)
      begin
        // [load_store.n:145]
        ag1m_out = $signed({{8{__CTsbyte_cstP4_ID_in_opd[7]}}, __CTsbyte_cstP4_ID_in_opd});
      end
      3'b011 : // (ag1m_copy0___CTword_cstV1_ID)
      begin
        // [load_store.n:76]
        ag1m_out = 16'sb0000000000000001;
      end
      3'b100 : // (ag1m_copy0___CTword_cstVm1_ID)
      begin
        // [load_store.n:77]
        ag1m_out = 16'sb1111111111111111;
      end
      3'b101 : // (ag1m_copy0___CTword_cstP16_ID)
      begin
        // [load_store.n:138]
        ag1m_out = __CTword_cstP16_ID_in_opd;
      end
      default :
        ; // null
    endcase

  end

endmodule
