
// File generated by Go version O-2018.09#f5599cac26#190121, Tue May 28 10:45:21 2024
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// go -B -I../lib -F -D__tct_patch__=300 -Verilog -otmicro_vlog -cgo_options.cfg -Itmicro_vlog/tmp_pdg -updg -updg_controller tmicro



`timescale 1ns/1ps

// module mux_offs : mux_offs
module mux_offs
  ( input                   ohe_selector_E1,
    input                   ohe_selector_ID,
    input      signed [7:0] __CTsbyte_cstP8_E1_in, // sbyte
    input      signed [7:0] __CTsbyte_cstP8_ID_in, // sbyte
    output reg signed [7:0] offs_out // sbyte
  );


  always @ (*)

  begin : p_mux_offs


    reg    signed [7:0] __CTsbyte_cstP8_E1_in_opd; // sbyte
    reg    signed [7:0] __CTsbyte_cstP8_ID_in_opd; // sbyte

    offs_out = 8'b00000000; // hw_init

    // operand isolation
    if (ohe_selector_E1 == 0)
    begin
      __CTsbyte_cstP8_E1_in_opd = 0;
    end
    else
    begin
      __CTsbyte_cstP8_E1_in_opd = __CTsbyte_cstP8_E1_in;
    end
    if (ohe_selector_ID == 0)
    begin
      __CTsbyte_cstP8_ID_in_opd = 0;
    end
    else
    begin
      __CTsbyte_cstP8_ID_in_opd = __CTsbyte_cstP8_ID_in;
    end


    if (ohe_selector_E1) // (offs_copy0___CTsbyte_cstP8_E1)
    begin
      // [control.n:96]
      offs_out = __CTsbyte_cstP8_E1_in_opd;
    end

    if (ohe_selector_ID) // (offs_copy0___CTsbyte_cstP8_ID)
    begin
      // [control.n:76][control.n:83]
      offs_out = __CTsbyte_cstP8_ID_in_opd;
    end

  end

endmodule
