
// File generated by Go version O-2018.09#f5599cac26#190121, Tue May 28 10:45:21 2024
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// go -B -I../lib -F -D__tct_patch__=300 -Verilog -otmicro_vlog -cgo_options.cfg -Itmicro_vlog/tmp_pdg -updg -updg_controller tmicro



`timescale 1ns/1ps

// module mux___LC_lcw_wad : mux___LC_lcw_wad
module mux___LC_lcw_wad
  ( input            ohe_selector_E1,
    input            LC_lcw_cntrl_nxtpc_pdg_en_in, // std_logic
    input      [1:0] LC_lcw_cntrl_nxtpc_pdg_w_a_in, // uint2
    input      [1:0] lfw_in, // uint2
    output reg [1:0] __LC_lcw_wad_out // uint2
  );


  always @ (*)

  begin : p_mux___LC_lcw_wad


    reg    [1:0] lfw; // uint2

    __LC_lcw_wad_out = 0;

    // operand isolation
    if (ohe_selector_E1 == 0)
    begin
      lfw = 0;
    end
    else
    begin
      lfw = lfw_in;
    end


    // (__LC_lcw_wad_cp_LC_lcw_cntrl_nxtpc_pdg_w_a_LC_lcw_cntrl_nxtpc_pdg_en)
    if (LC_lcw_cntrl_nxtpc_pdg_en_in)
    begin
      __LC_lcw_wad_out = LC_lcw_cntrl_nxtpc_pdg_w_a_in;
    end

    if (ohe_selector_E1) // (__LC_lcw_wad_copy0_lfw_E1)
    begin
      // [control.n:180]
      __LC_lcw_wad_out = lfw;
    end

  end

endmodule
