
// File generated by Go version O-2018.09#f5599cac26#190121, Tue May 28 10:45:21 2024
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// go -B -I../lib -F -D__tct_patch__=300 -Verilog -otmicro_vlog -cgo_options.cfg -Itmicro_vlog/tmp_pdg -updg -updg_controller tmicro



`timescale 1ns/1ps

// module mux___dm_addr_pipe_w : mux___dm_addr_pipe_w
module mux___dm_addr_pipe_w
  ( input              [1:0] bin_selector_ID,
    input                    ocd_st_DM_in, // bool
    input      signed [15:0] ag1p_in, // word
    input      signed [15:0] ag1q_in, // word
    input             [15:0] ocd_addr_r_in, // addr
    output reg        [15:0] __dm_addr_pipe_w_out // addr
  );


  always @ (*)

  begin : p_mux___dm_addr_pipe_w


    reg    signed [15:0] ag1p; // word
    reg    signed [15:0] ag1q; // word

    __dm_addr_pipe_w_out = 0;

    // operand isolation
    if (bin_selector_ID == 0)
    begin
      ag1p = 0;
      ag1q = 0;
    end
    else
    begin
      ag1p = ag1p_in;
      ag1q = ag1q_in;
    end


    // (dm_addr_pipe_copy0_ocd_addr_r_ocd_st_DM_ID_alw)
    if (ocd_st_DM_in)
    begin
      // [ocd_if.n:32]
      __dm_addr_pipe_w_out = ocd_addr_r_in;
    end

    case (bin_selector_ID)
      2'b01 : // (dm_addr_pipe_copy0_ag1p_ID)
      begin
        // [load_store.n:96]
        __dm_addr_pipe_w_out = $unsigned(ag1p);
      end
      2'b10 : // (dm_addr_pipe_copy0_ag1q_ID)
      begin
        // [load_store.n:54]
        __dm_addr_pipe_w_out = $unsigned(ag1q);
      end
      default :
        ; // null
    endcase

  end

endmodule
