
// File generated by Go version O-2018.09#f5599cac26#190121, Tue May 28 10:45:21 2024
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// go -B -I../lib -F -D__tct_patch__=300 -Verilog -otmicro_vlog -cgo_options.cfg -Itmicro_vlog/tmp_pdg -updg -updg_controller tmicro



`timescale 1ns/1ps

// module mux_lfw : mux_lfw
module mux_lfw
  ( input            ohe_selector_E1,
    input            LF_lfw_cntrl_nxtpc_pdg_en_in, // std_logic
    input      [1:0] lfw1_in, // uint2
    input      [1:0] lfw2_in, // uint2
    output reg [1:0] lfw_out // uint2
  );


  always @ (*)

  begin : p_mux_lfw


    reg    [1:0] lfw2; // uint2

    lfw_out = 0;

    // operand isolation
    if (ohe_selector_E1 == 0)
    begin
      lfw2 = 0;
    end
    else
    begin
      lfw2 = lfw2_in;
    end


    // (lfw_copy_lfw1_LF_lfw_cntrl_nxtpc_pdg_en)
    if (LF_lfw_cntrl_nxtpc_pdg_en_in)
    begin
      lfw_out = lfw1_in;
    end

    if (ohe_selector_E1) // (lfw_copy_lfw2_E1)
    begin
      // [control.n:177][control.n:211]
      lfw_out = lfw2;
    end

  end

endmodule
