
// File generated by Go version O-2018.09#f5599cac26#190121, Tue May 28 10:45:21 2024
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// go -B -I../lib -F -D__tct_patch__=300 -Verilog -otmicro_vlog -cgo_options.cfg -Itmicro_vlog/tmp_pdg -updg -updg_controller tmicro



`timescale 1ns/1ps

// module mux_dm_addr : mux_dm_addr
module mux_dm_addr
  ( input                    ohe_selector_E1,
    input              [1:0] bin_selector_ID,
    input                    __ocd_st_DME1_r_in, // bool
    input                    ocd_ld_DM_in, // bool
    input             [15:0] __dm_addr_pipe_r_in, // addr
    input      signed [15:0] ag1p_in, // word
    input      signed [15:0] ag1q_in, // word
    input             [15:0] ocd_addr_r_in, // addr
    output reg        [15:0] dm_addr_out // addr
  );


  always @ (*)

  begin : p_mux_dm_addr


    reg    signed [15:0] ag1p; // word
    reg    signed [15:0] ag1q; // word

    dm_addr_out = 0;

    // operand isolation
    if (bin_selector_ID == 0)
    begin
      ag1p = 0;
      ag1q = 0;
    end
    else
    begin
      ag1p = ag1p_in;
      ag1q = ag1q_in;
    end


    // (dm_addr_copy0_dm_addr_pipe___ocd_st_DME1_r_E1_alw, dm_addr_copy0_ocd_addr_r_ocd_ld_DM_ID_alw)
    if (__ocd_st_DME1_r_in)
    begin
      // [ocd_if.n:34]
      dm_addr_out = __dm_addr_pipe_r_in;
    end
    if (ocd_ld_DM_in)
    begin
      // [ocd_if.n:28]
      dm_addr_out = ocd_addr_r_in;
    end

    if (ohe_selector_E1) // (dm_addr_copy0_dm_addr_pipe_E1)
    begin
      // [load_store.n:56][load_store.n:98]
      dm_addr_out = __dm_addr_pipe_r_in;
    end

    case (bin_selector_ID)
      2'b01 : // (dm_addr_copy0_ag1p_ID)
      begin
        // [load_store.n:92]
        dm_addr_out = $unsigned(ag1p);
      end
      2'b10 : // (dm_addr_copy0_ag1q_ID)
      begin
        // [load_store.n:50]
        dm_addr_out = $unsigned(ag1q);
      end
      default :
        ; // null
    endcase

  end

endmodule
