
// File generated by noodle version O-2018.09#f5599cac26#190121, Tue May 28 12:03:13 2024
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// noodle -Pc -B -Iisg +wisg -Iruntime/include -D__tct_patch__=300 -D__chess__ -D__programmers_view__ tzscale

// File: standalone_intrinsics.c
// Test standalone intrinsics  (in global namespace)
// (Outputs that cannot be returned as function parameters are discarded)

extern "C" {

long long intrc___slonglong_div_remainder___slonglong___slonglong___slonglong(long long a0, long long a1, long long & a2)
    { return div_remainder(a0, a1, a2); }

unsigned long long intrc___ulonglong_div_remainder___ulonglong___ulonglong___ulonglong(unsigned long long a0, unsigned long long a1, unsigned long long & a2)
    { return div_remainder(a0, a1, a2); }

void intrc_void_float_raise___sint(int a0)
    { float_raise(a0); }

int intrc___sint_float32_is_signaling_nan___uint(float32 a0)
    { return float32_is_signaling_nan(a0); }

int intrc___sint_float64_is_signaling_nan_dint(float64 a0)
    { return float64_is_signaling_nan(a0); }

int intrc___sint_f32_to_i32___uint(float32 a0)
    { return f32_to_i32(a0); }

float32 intrc___uint_i32_to_f32___sint(int a0)
    { return i32_to_f32(a0); }

float32 intrc___uint_f32_add___uint___uint(float32 a0, float32 a1)
    { return f32_add(a0, a1); }

float32 intrc___uint_f32_sub___uint___uint(float32 a0, float32 a1)
    { return f32_sub(a0, a1); }

float32 intrc___uint_f32_mul___uint___uint(float32 a0, float32 a1)
    { return f32_mul(a0, a1); }

float32 intrc___uint_f32_div___uint___uint(float32 a0, float32 a1)
    { return f32_div(a0, a1); }

int intrc_bool_f32_le___uint___uint(float32 a0, float32 a1)
    { return f32_le(a0, a1); }

int intrc_bool_f32_lt___uint___uint(float32 a0, float32 a1)
    { return f32_lt(a0, a1); }

int intrc_bool_f32_eq___uint___uint(float32 a0, float32 a1)
    { return f32_eq(a0, a1); }

int intrc___sint_f64_to_i32_dint(float64 a0)
    { return f64_to_i32(a0); }

float64 intrc_dint_i32_to_f64___sint(int a0)
    { return i32_to_f64(a0); }

float64 intrc_dint_f32_to_f64___uint(float32 a0)
    { return f32_to_f64(a0); }

float32 intrc___uint_f64_to_f32_dint(float64 a0)
    { return f64_to_f32(a0); }

float64 intrc_dint_f64_add_dint_dint(float64 a0, float64 a1)
    { return f64_add(a0, a1); }

float64 intrc_dint_f64_sub_dint_dint(float64 a0, float64 a1)
    { return f64_sub(a0, a1); }

float64 intrc_dint_f64_mul_dint_dint(float64 a0, float64 a1)
    { return f64_mul(a0, a1); }

float64 intrc_dint_f64_div_dint_dint(float64 a0, float64 a1)
    { return f64_div(a0, a1); }

int intrc_bool_f64_le_dint_dint(float64 a0, float64 a1)
    { return f64_le(a0, a1); }

int intrc_bool_f64_lt_dint_dint(float64 a0, float64 a1)
    { return f64_lt(a0, a1); }

int intrc_bool_f64_eq_dint_dint(float64 a0, float64 a1)
    { return f64_eq(a0, a1); }

int intrc___sint_ext_mac____sint___sint___sint(int a0, int a1, int a2)
    { return ext_mac_(a0, a1, a2); }

int intrc___sint__ml_v2short_v2short(v2short a0, v2short a1)
    { return operator*(a0, a1); }

int intrc___sint_ext_dotp__v2short_v2short___sint(v2short a0, v2short a1, int a2)
    { return ext_dotp_(a0, a1, a2); }


} //extern "C"  (28 functions)
