
// File generated by Go version O-2018.09#f5599cac26#190121, Tue May 28 10:45:21 2024
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// go -B -I../lib -F -D__tct_patch__=300 -Verilog -otmicro_vlog -cgo_options.cfg -Itmicro_vlog/tmp_pdg -updg -updg_controller tmicro



`timescale 1ns/1ps

// module mem_PM : mem_PM
module mem_PM
  ( input       [1:0] bin_selector_E1,
    input             ohe_selector_ID,
    input             __ocd_st_PME1_r_in, // bool
    input             ocd_ld_PM_in, // bool
    input             pm_ld_pdg_en_in, // std_logic
    input      [15:0] pm_addr_dp_in, // addr
    input      [15:0] pm_read_in, // iword
    input      [15:0] pm_write_dp_in, // iword
    output reg [15:0] pm_addr_out, // addr
    output reg        pm_ld_out, // std_logic
    output reg [15:0] pm_read_dp_out, // iword
    output reg        pm_st_out, // std_logic
    output reg [15:0] pm_write_out // iword
  );


  always @ (*)

  begin : p_mem_PM

    pm_addr_out = 0;
    pm_ld_out = 0;
    // pm_read_dp_out = 0;
    pm_st_out = 0;
    pm_write_out = 0;

    // (cp_extad_PM_st_pm_write_pm_addr___ocd_st_PME1_r_E1_alw, cp_extin_pm_read_ld_PM_pm_addr_ocd_ld_PM_ID_alw, cp_extout_PM_st_pm_write_pm_addr___ocd_st_PME1_r_E1_alw, cp_extad_pm_read_ld_PM_pm_addr_ocd_ld_PM_ID_alw, cp_extin_pm_read_rd_PM_pm_addr_pm_ld_pdg_en, mem_enab_PM_st_pm_write_pm_addr___ocd_st_PME1_r_E1_alw, mem_enab_pm_read_ld_PM_pm_addr_ocd_ld_PM_ID_alw, mem_enab_pm_read_rd_PM_pm_addr_pm_ld_pdg_en, cp_extad_pm_read_rd_PM_pm_addr_pm_ld_pdg_en)
    if (__ocd_st_PME1_r_in)
    begin
      // [ocd_if.n:46]
      pm_addr_out = pm_addr_dp_in;
    end
    // [ocd_if.n:40](ocd_if.n:39)
    pm_read_dp_out = pm_read_in;
    if (__ocd_st_PME1_r_in)
    begin
      // [ocd_if.n:46]
      pm_write_out = pm_write_dp_in;
    end
    if (ocd_ld_PM_in)
    begin
      // [ocd_if.n:40](ocd_if.n:39)
      pm_addr_out = pm_addr_dp_in;
    end
    if (__ocd_st_PME1_r_in)
    begin
      // [ocd_if.n:46]
      pm_st_out = 1'b1;
    end
    if (ocd_ld_PM_in)
    begin
      // [ocd_if.n:40](ocd_if.n:39)
      pm_ld_out = 1'b1;
    end
    if (pm_ld_pdg_en_in)
    begin
      pm_ld_out = 1'b1;
      pm_addr_out = pm_addr_dp_in;
    end

    case (bin_selector_E1)
      2'b01 : // (mem_enab_PM_st_pm_write_pm_addr_E1, cp_extad_PM_st_pm_write_pm_addr_E1, cp_extout_PM_st_pm_write_pm_addr_E1)
      begin
        // [load_store.n:130]
        pm_st_out = 1'b1;
        // [load_store.n:130]
        pm_addr_out = pm_addr_dp_in;
        // [load_store.n:130]
        pm_write_out = pm_write_dp_in;
      end
      2'b10 : // (cp_extin_pm_read_ld_PM_pm_addr_ID)
      begin
        // [load_store.n:116]
        pm_read_dp_out = pm_read_in;
      end
      default :
        ; // null
    endcase

    if (ohe_selector_ID) // (mem_enab_pm_read_ld_PM_pm_addr_ID, cp_extad_pm_read_ld_PM_pm_addr_ID)
    begin
      // [load_store.n:116]
      pm_ld_out = 1'b1;
      // [load_store.n:116]
      pm_addr_out = pm_addr_dp_in;
    end

  end

endmodule
