
# File generated by Go version O-2018.09#f5599cac26#190121, Tue May 28 10:45:22 2024
# Copyright 2014-2018 Synopsys, Inc. All rights reserved.
# go -B -I../lib -F -D__tct_patch__=300 -Verilog -otmicro_vlog -cgo_options.cfg -Itmicro_vlog/tmp_pdg -updg -updg_controller tmicro



set appdir "."
# read appdir from APPDIR env variable, if exists
catch { set appdir $env(APPDIR) }

set appname "data"
# read appname from APP env variable, if exists
catch { set appname $env(APP) }

# generate appname.cfg
set f_appname [open "appname.cfg" w]
puts $f_appname "$appdir/$appname"
close $f_appname

# now get exit addresses
set exit_addr_list {}
set exitfname "$appdir/$appname.exit"
if {![file exists $exitfname]} {
    puts "** Error: File '$exitfname' not found!"
    finish
}
puts "** Info: Reading exit address(es) from '$exitfname'"
set f_exit [open $exitfname r]
while {[gets $f_exit line] >= 0} {
    lappend exit_addr_list $line
}
close $f_exit
if {[llength $exit_addr_list] == 0} {
    puts "** Error: No exit address in file '$exitfname'!"
    finish
}

# set stop conditions
foreach exit_addr $exit_addr_list {
    set i_exit_addr [expr $exit_addr]
    stop -condition {/test_bench/inst_tmicro/inst_reg_PC/pcr_out = $i_exit_addr }
    puts "** Info: Breakpoint set at: $i_exit_addr"
}

power -gate_level rtl_on mda
power  test_bench.inst_tmicro
power -enable
# run (max. 1000s):
run 1000000000000 ns
power -disable
power -report tmicro.saif 1e-12 inst_tmicro

# get number of run cycles:
set cycles_run [get //test_bench/inst_tmicro/inst_reg_PC/cycles]
puts "** Info: Run $cycles_run cycles."

# cleanup
file delete "appname.cfg"

finish
