
# File generated by Go version O-2018.09#f5599cac26#190121, Tue May 28 10:45:22 2024
# Copyright 2014-2018 Synopsys, Inc. All rights reserved.
# go -B -I../lib -F -D__tct_patch__=300 -Verilog -otmicro_vlog -cgo_options.cfg -Itmicro_vlog/tmp_pdg -updg -updg_controller tmicro



set hdlprx tmicro_vlog
# read hdlprx from HDLPRX env variable, if exists
catch { set hdlprx $env(HDLPRX) }

set appdir "."
# read appdir from APPDIR env variable, if exists
catch { set appdir $env(APPDIR) }

set appname "data"
# read appname from APP env variable, if exists
catch { set appname $env(APP) }
puts "** Info: Using hdlprx='$hdlprx', appdir='$appdir', appname='$appname'"

# generate appname.cfg
set f_appname [open "appname.cfg" w]
puts $f_appname "$appdir/$appname"
close $f_appname
# generate rcdname.cfg
set f_rcdname [open "rcdname.cfg" w]
puts $f_rcdname "$appdir/$appname.$hdlprx.rcd"
close $f_rcdname
# delete potential existing rcd file
file delete "$appdir/$appname.$hdlprx.rcd"

# now read the cycle count
set num_cycles 0
if {![file exists "$appdir/$appname.cycle_count"]} {
    puts "** Error: File '$appdir/$appname.cycle_count' not found!"
    finish
}
puts "** Info: Reading cycle_count from file '$appdir/$appname.cycle_count'"
set f_cycle_count [open "$appdir/$appname.cycle_count" r]
gets $f_cycle_count line
close $f_cycle_count
set num_cycles [expr $line]

# set stop conditions
force /test_bench/inst_tmicro/inst_reg_PC/max_cycles $num_cycles

# and run:
puts "** Info: Simulating $num_cycles cycles."
run
# run one additional ps to log changes of other regs:
run 1 ps

# cleanup
file delete "appname.cfg"
file delete "rcdname.cfg"

finish
