
// File generated by Go version O-2018.09#f5599cac26#190121, Tue May 28 10:45:21 2024
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// go -B -I../lib -F -D__tct_patch__=300 -Verilog -otmicro_vlog -cgo_options.cfg -Itmicro_vlog/tmp_pdg -updg -updg_controller tmicro



#include "pdc_commands.h"

#include <stdlib.h>

void pdc_commands::init_bpwp_codes(int core_id)
{
    if (core_id > max_core_id) {
        cerr << "invalid core_id (maximum coreid = " << max_core_id << "): "
             << core_id << '\n';
        exit(1);
    }
    // core ID
    int cid = core_id << 11;

    // configuration parameters:
    dbg_range_watchpoints = 0;
    dbg_ldst_watchpoints = 0;

    // breakpoint instruction opcodes     : 000001bbbii (11 bits)
    bp_enable_instr [0] = cid | 0x020;
    bp_export_instr [0] = cid | 0x021;
    bp_disable_instr[0] = cid | 0x022;
    bp_enable_instr [1] = cid | 0x024;
    bp_export_instr [1] = cid | 0x025;
    bp_disable_instr[1] = cid | 0x026;
    bp_enable_instr [2] = cid | 0x028;
    bp_export_instr [2] = cid | 0x029;
    bp_disable_instr[2] = cid | 0x02a;
    bp_enable_instr [3] = cid | 0x02c;
    bp_export_instr [3] = cid | 0x02d;
    bp_disable_instr[3] = cid | 0x02e;

    // watchpoint instruction opcodes     : 0001bbbmmmm (11 bits)
    bp_watch_store_instr["PM"][0] = cid | 0x080;
    bp_watch_store_instr["PM"][1] = cid | 0x090;
    bp_watch_store_instr["PM"][2] = cid | 0x0a0;
    bp_watch_store_instr["PM"][3] = cid | 0x0b0;
    bp_watch_store_instr["DM"][0] = cid | 0x081;
    bp_watch_store_instr["DM"][1] = cid | 0x091;
    bp_watch_store_instr["DM"][2] = cid | 0x0a1;
    bp_watch_store_instr["DM"][3] = cid | 0x0b1;
}
