
// File generated by Go version O-2018.09#f5599cac26#190121, Tue May 28 10:45:21 2024
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// go -B -I../lib -F -D__tct_patch__=300 -Verilog -otmicro_vlog -cgo_options.cfg -Itmicro_vlog/tmp_pdg -updg -updg_controller tmicro



#ifndef _pdc_opcodes_h
#define _pdc_opcodes_h

// register widths
const int DBG_DATA_REG_WIDTH          = 16;
const int DBG_ADDR_REG_WIDTH          = 16;
const int DBG_INSTR_REG_WIDTH         = 16;
const int DBG_STATUS_REG_WIDTH        = 16;
const int DBG_CONTEXT_REG_WIDTH       = 0;

// status register bit indices
const int DBG_MODE_INDX               = 0;
const int DBG_BP_HIT_INDX             = 5;
const int DBG_BREAKIN_INDX            = 6;
const int DBG_BREAKOUT_INDX           = 7;
const int DBG_SWBREAK_INDX            = 8;

// register indices
const int DBG_DATA_REG_INDX           = 0x0;
const int DBG_ADDR_REG_INDX           = 0x1;
const int DBG_INSTR_REG_INDX          = 0x2;
const int DBG_STATUS_REG_INDX         = 0x3;

// register opcodes                   : 0000000rrrr (11 bits)
const int DBG_DATA_REG_INSTR          = 0x000;
const int DBG_ADDR_REG_INSTR          = 0x001;
const int DBG_INSTR_REG_INSTR         = 0x002;
const int DBG_STATUS_REG_INSTR        = 0x003;
const int DBG_CONTEXT_REG_INSTR       = 0x004;

// instruction opcodes                : 0000001iiii (11 bits)
const int DBG_REQUEST_INSTR           = 0x011;
const int DBG_RESUME_INSTR            = 0x012;
const int DBG_RESET_INSTR             = 0x013;
const int DBG_STEP_INSTR              = 0x014;
const int DBG_EXECUTE_INSTR           = 0x015;
const int DBG_STEPDI_INSTR            = 0x016;

// breakpoint instruction opcodes     : 000001bbbii (11 bits)
const int DBG_BP0_ENABLE_INSTR        = 0x020;
const int DBG_BP0_EXPORT_INSTR        = 0x021;
const int DBG_BP0_DISABLE_INSTR       = 0x022;
const int DBG_BP1_ENABLE_INSTR        = 0x024;
const int DBG_BP1_EXPORT_INSTR        = 0x025;
const int DBG_BP1_DISABLE_INSTR       = 0x026;
const int DBG_BP2_ENABLE_INSTR        = 0x028;
const int DBG_BP2_EXPORT_INSTR        = 0x029;
const int DBG_BP2_DISABLE_INSTR       = 0x02a;
const int DBG_BP3_ENABLE_INSTR        = 0x02c;
const int DBG_BP3_EXPORT_INSTR        = 0x02d;
const int DBG_BP3_DISABLE_INSTR       = 0x02e;

// watchpoint instruction opcodes     : 0001bbbmmmm (11 bits)
const int DBG_WP0_ST_PM_ENABLE_INSTR  = 0x080;
const int DBG_WP1_ST_PM_ENABLE_INSTR  = 0x090;
const int DBG_WP2_ST_PM_ENABLE_INSTR  = 0x0a0;
const int DBG_WP3_ST_PM_ENABLE_INSTR  = 0x0b0;
const int DBG_WP0_ST_DM_ENABLE_INSTR  = 0x081;
const int DBG_WP1_ST_DM_ENABLE_INSTR  = 0x091;
const int DBG_WP2_ST_DM_ENABLE_INSTR  = 0x0a1;
const int DBG_WP3_ST_DM_ENABLE_INSTR  = 0x0b1;

// extra command opcodes              : 00100000ccc (11 bits)
const int DBG_TRACE_RD_INSTR          = 0x100;
const int DBG_TRACE_RD_CNT_INSTR      = 0x101;
const int DBG_TRACE_CFG_WR_INSTR      = 0x102;

// load/store instruction opcodes     : 000010iiiii (11 bits)
const int DBG_PM_LOAD_INSTR           = 0x040;
const int DBG_PM_STORE_INSTR          = 0x041;
const int DBG_DM_LOAD_INSTR           = 0x042;
const int DBG_DM_STORE_INSTR          = 0x043;

// common instructions "11111"...
const int DBG_SYNC_REQUEST_INSTR      = 0xf811;
const int DBG_SYNC_RESUME_INSTR       = 0xf812;
const int DBG_SYNC_RESET_INSTR        = 0xf813;
const int DBG_SYNC_STEP_INSTR         = 0xf814;
const int DBG_SYNC_STEPDI_INSTR       = 0xf816;
const int DBG_TRACE_RD_SYNC_INSTR     = 0xf900;
const int DBG_TRACE_RD_CNT_SYNC_INSTR = 0xf901;
const int DBG_TRACE_CFG_WR_SYNC_INSTR = 0xf902;

#endif

