
// File generated by Go version O-2018.09#f5599cac26#190121, Tue May 28 10:45:21 2024
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// go -B -I../lib -F -D__tct_patch__=300 -Verilog -otmicro_vlog -cgo_options.cfg -Itmicro_vlog/tmp_pdg -updg -updg_controller tmicro



`timescale 1ns/1ps

// module pipe1 : pipe___pm_addr_pipe pipe___dm_addr_pipe
module pipe1
  ( input         clock,
    input  [15:0] in0, // addr __pm_addr_pipe_w __dm_addr_pipe_w
    output [15:0] out0 // addr __pm_addr_pipe_r __dm_addr_pipe_r
  );


  reg [15:0] pipe_val_out0;

  assign out0 = pipe_val_out0; // 1:__pm_addr_pipe_r 2:__dm_addr_pipe_r


  always @ (posedge clock)
  begin : p_pipe1
    // 1:(go___pm_addr_pipe_r)
    // 2:(go___dm_addr_pipe_r)
    pipe_val_out0 <= in0;

  end
endmodule
