
; File generated by darts version O-2018.09#f5599cac26#190121, Tue May 28 10:42:09 2024
; Copyright 2014-2018 Synopsys, Inc. All rights reserved.
; darts -B -I. +p -d -h -Iruntime/include -D__tct_patch__=300 +Ihex Release/tmicro_mul_i32.o tmicro

; Release: ipd O-2018.09-SP3
.text_segment_name
.text global 0 __mul_i32
	/*      0 0x1854 */    muluu (r6,r7),r2,r4
	/*      1 0x18dc */    macl (r7),r3,r4
	/*      2 0x2506 */    mv r0,r6
	/*      3 0x2ec0 */    rtd 
	/*      4 0x18ea */    macl (r7),r5,r2
.label __mul_i32__end
	/*      5 0x2517 */    mv r1,r7

