
; File generated by darts version O-2018.09#f5599cac26#190121, Tue May 28 10:42:10 2024
; Copyright 2014-2018 Synopsys, Inc. All rights reserved.
; darts -B -I. +p -d -h -Iruntime/include -D__tct_patch__=300 +Ihex Release/tmicro_init.o tmicro

; Release: ipd O-2018.09-SP3
.text_segment_name
.text global 0 tmicro_init
.label tmicro_init__end last
	/*      0 0x241a */    mvi sp,_sp_start_DM
	/*      1 0x0000 */    /* MW */

.data_segment_name
.bss global 0 _main_argv_area DM 256

.undef global data _sp_start_DM

.undef global data _sp_start_DM

