# This file was automatically generated by open_hw_platform
  set_param bd.ForceAppCoreUpgrade 1
  set_param project.enablePRFlowIPI 1
  set_param project.gatelevelSubdesign 1
  set_param project.enableVersalIPIPRFlow 1
  set_param board.repoPaths /scratch/ex_hetero_vitis_soc_12fs24/src/platform/basic/design_1_wrapper/hw_platform/board
