# This file was automatically generated by open_hw_platform
  set_property board_part_repo_paths /scratch/ex_hetero_vitis_soc_12fs24/src/platform/basic/design_1_wrapper/hw_platform/board [current_project]
  set_property board_part digilentinc.com:zedboard:part0:1.0 [current_project]
  lappend ip_repo_paths /scratch/ex_hetero_vitis_soc_12fs24/src/platform/basic/design_1_wrapper/hw_platform/ipcache
  set_property ip_repo_paths $ip_repo_paths [current_project]
  if { [catch {update_ip_catalog} result] } {
     puts "update_ip_catalog failed: $result"
  }
  set dr_bd_file [file tail [lindex [get_files *.bd] 0]]
  config_ip_cache -export [get_ips -all -of_object [get_files $dr_bd_file]]
  open_bd_design -auto_upgrade [get_files $dr_bd_file]
