
// File generated by Go version O-2018.09#f5599cac26#190121, Tue May 28 10:45:21 2024
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// go -B -I../lib -F -D__tct_patch__=300 -Verilog -otmicro_vlog -cgo_options.cfg -Itmicro_vlog/tmp_pdg -updg -updg_controller tmicro



`timescale 1ns/1ps

// module reg_SRa : reg_SRa
module reg_SRa
  // synopsys translate_off
  #(parameter reg_log = 1'b1,
    parameter reg_log_name = "SRa"
  )
  // synopsys translate_on
  ( input            clock,
    input      [1:0] bin_selector_E1,
    input      [1:0] __pm_read_w_SR_el3_in, // uint2
    input      [1:0] dm_read_rec4_in, // uint2
    input      [1:0] wbus_rec11_in, // uint2
    output reg [1:0] __pm_write_r_SR_el3_out, // uint2
    output reg [1:0] dm_write_rec4_out, // uint2
    output reg [1:0] wbus_rec4_out // uint2
  );


  reg [1:0] reg_val;

  reg [1:0] reg_val_next;

  reg  reg_write_enab;


  // synopsys translate_off

  reg reg_write_log;
  reg old_reg_write_log;
  initial reg_write_log     = 1'b0;
  initial old_reg_write_log = 1'b0;

  always @ (negedge clock)
  begin : p_reg_SRa_log


    if (reg_log)
    begin
      if (reg_write_log !=old_reg_write_log)
      begin
        $fdisplay(tmicro.inst_reg_PC.log_file, "%s = %0d", reg_log_name, reg_val);
      end
      old_reg_write_log <= reg_write_log;
    end
  end
  // synopsys translate_on

  always @ (*)
  begin : p_read_reg_SRa

    // __pm_write_r_SR_el3_out = 0;
    // dm_write_rec4_out = 0;
    // wbus_rec4_out = 0;

    // (wbus_rd_SR_E1_t3)
    // [move.n:48][move.n:96][control.n:225][dma.n:51](tmicro.n:132)
    wbus_rec4_out = reg_val;

    // (dm_write_rd_SR_E1_t3)
    // [load_store.n:57][load_store.n:99](tmicro.n:132)
    dm_write_rec4_out = reg_val;

    // (__pm_write_r_SR_rd_SR_E1_t3)
    // [load_store.n:130](tmicro.n:132)
    __pm_write_r_SR_el3_out = reg_val;

  end

  always @ (*)
  begin : p_write_combin_reg_SRa

    reg_write_enab = 0;
    reg_val_next = 0;


    case (bin_selector_E1)
      2'b01 : // (SR_wr_wbus_E1_t3)
      begin
        // [move.n:48][move.n:55][move.n:62][move.n:106][control.n:238][dma.n:70](tmicro.n:132)
        reg_write_enab = 1'b1;
        reg_val_next = wbus_rec11_in;
      end
      2'b10 : // (SR_wr_dm_read_E1_t3)
      begin
        // [load_store.n:51][load_store.n:93](tmicro.n:132)
        reg_write_enab = 1'b1;
        reg_val_next = dm_read_rec4_in;
      end
      2'b11 : // (SR_wr___pm_read_w_SR_E1_t3)
      begin
        // [load_store.n:116](tmicro.n:132)
        reg_write_enab = 1'b1;
        reg_val_next = __pm_read_w_SR_el3_in;
      end
      default :
        ; // null
    endcase

  end

  always @ (posedge clock)
  begin : p_write_reg_SRa

    if (reg_write_enab)
    begin
      reg_val <= reg_val_next;
      // synopsys translate_off
      reg_write_log <= ~reg_write_log;
      // synopsys translate_on
    end
  end

endmodule
